# Inspired by https://mherman.org/blog/dockerizing-a-react-app/
FROM node:12.10.0-alpine

ARG GROUP_ID=1000
ARG USER_ID=1000

#############
# As `root` #
#############

RUN \
  apk add --no-cache \
    dumb-init \
    make

ENV HOME=/home/node
RUN \
  mkdir ${HOME}/app && \
  chown node:node ${HOME}/app && \
  ln -s ${HOME}/app /app

#############
# As `node` #
#############
USER node
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY \
  --chown=node:node \
  package.json ./
RUN npm install

EXPOSE 3000
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "start"]
