import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
  overwrite: true,
  schema: "./type-defs.graphqls",
  documents: "./queries/*.graphql",
  // Don't exit with non-zero status when there are no documents
  ignoreNoDocuments: true,
  generates: {
    // Inspired by https://www.apollographql.com/docs/react/development-testing/graphql-codegen#generating-precompiled-graphql-documents-with-their-type-definitions
    "./__generated__/graphql.ts": {
      plugins: ["typescript"],
    },
    "./queries/": {
      preset: "near-operation-file",
      presetConfig: {
        // This should be the file generated by the "typescript" plugin above,
        // relative to the directory specified for this configuration
        baseTypesPath: "../__generated__/graphql.ts",
      },
      plugins: ["typescript-operations", "typed-document-node"],
      config: {
        avoidOptionals: {
          // Use `null` for nullable fields instead of optionals
          field: true,
          // Allow nullable input fields to remain unspecified
          inputValue: false,
        },
        // Use `unknown` instead of `any` for unconfigured scalars
        defaultScalarType: "unknown",
        // Apollo Client always includes `__typename` fields
        nonOptionalTypename: true,
        // Apollo Client doesn't add the `__typename` field to root types so
        // don't generate a type for the `__typename` for root operation types.
        skipTypeNameForRoot: true,
        // ...
        strictScalars: true,
        scalars: {
          ID: {
            input: "string",
            output: "string",
          },
          Any: "unknown",
          Byte: "number",
          DateTime: "string",
          DateTimeZone: "string",
          Decimal: "string",
          Duration: "string",
          Locale: "string",
          Long: "number",
          NonNegativeInt: "number",
          Short: "number",
          TimeSpan: "string",
          Upload: "unknown",
          Url: "string",
          Uuid: "string",
        },
        useTypeImports: true,
        // immutableTypes: true,
        // nullability: true,
      },
    },
    "./__generated__/fragmentMatcherTypes.ts": {
      plugins: ["fragment-matcher"],
      config: {
        module: "es2015",
        apolloClientVersion: 3,
        useExplicitTyping: false,
        deterministic: true,
      },
    },
    // './queries/': {
    //   preset: 'near-operation-file',
    //   presetConfig: {
    //     extension: '.graphql.ts',
    //     baseTypesPath: '../__generated__/graphql.ts',
    //   },
    //   plugins: ['typescript-operations', 'typed-document-node'],
    // },
  },
};

export default config;
