# Inspired by https://nextjs.org/docs/deployment#docker-image

FROM node:14.17.3-buster-slim AS dependencies
WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:14.17.3-buster-slim AS build
WORKDIR /app
COPY ./ ./
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn build

FROM node:14.17.3-buster-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.env.local ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/next.config.js ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/public ./public
RUN npx --no-install next telemetry disable
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 --ingroup nodejs nextjs
RUN chown --recursive nextjs:nodejs /app/.next
USER nextjs
