# syntax=docker/dockerfile:1.21
# check=error=true
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

# Inspired by https://mherman.org/blog/dockerizing-a-react-app/

# https://hub.docker.com/_/node
FROM node:24.11-trixie-slim
SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]

#############
# As `root` #
#############

# For best practices on using `apt-get` see
# https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
RUN apt-get update \
  && apt-get install \
    --assume-yes \
    --no-install-recommends \
    make \
    tini \
    wget \
  && rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*

ENV HOME=/home/node
RUN mkdir --parents ${HOME}/app \
  && chown \
    node:node \
    ${HOME}/app \
  && ln --symbolic ${HOME}/app /app

#############
# As `node` #
#############
USER node
WORKDIR /app

ENV PATH=/app/node_modules/.bin:$PATH
COPY --chown=node:node ./package.json ./
COPY --chown=node:node ./yarn.lock ./
RUN yarn install \
  --pure-lockfile \
  && yarn cache clean

# Create empty directories for user `me` and group `us` to make the respective
# mounted volumes be owned by the user `me` and the group `us`.
RUN mkdir --parents \
  ./.next \
  ./__generated__ \
  ./node_modules

ENTRYPOINT ["/usr/bin/tini", "--"]
