# Inspired by https://mherman.org/blog/dockerizing-a-react-app/

FROM node:12.10.0-alpine
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./package.json
RUN npm add -g pnpm && \
    pnpm install
CMD ["pnpm", "run", "start"]
