# syntax=docker/dockerfile:1.21
# check=error=true
# The first line fixes the Dockerfile frontend used by BuildKit. For details
# see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

# Inspired by https://nextjs.org/docs/deployment#docker-image

FROM node:24.11-trixie-slim AS dependencies
SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get upgrade --assume-yes \
  && rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*
WORKDIR /app
COPY ./package.json ./yarn.lock ./
RUN yarn install --pure-lockfile

FROM node:24.11-trixie-slim AS build
SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]
RUN apt-get update \
  && apt-get upgrade --assume-yes \
  && rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*
WORKDIR /app
COPY ./ ./
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn build

FROM node:24.11-trixie-slim
SHELL ["/bin/bash", "-o", "errexit", "-o", "nounset", "-o", "pipefail", "-c"]
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/.env.local ./
COPY --from=build /app/.next ./.next
COPY --from=build /app/next.config.ts ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./
COPY --from=build /app/public ./public
RUN apt-get update \
  && apt-get upgrade --assume-yes \
  && apt-get install \
    --assume-yes \
    --no-install-recommends \
    wget \
  && rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*
RUN npx --no-install next telemetry disable
# hadolint ignore=DL3059 # Multiple consecutive `RUN` instructions.
RUN addgroup --system --gid 1001 nodejs \
  && adduser --system --uid 1001 --ingroup nodejs nextjs \
  && chown --recursive nextjs:nodejs /app/.next
USER nextjs
