# Inspired by https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp

###########
# BUILDTIME
###########
# https://hub.docker.com/_/microsoft-dotnet-core-sdk
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.302-alpine3.12 AS buildtime
WORKDIR /app

# copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore

# copy everything else and build app
COPY . .
WORKDIR /app
RUN dotnet publish -c Release -o out

#########
# RUNTIME
#########
# https://hub.docker.com/_/microsoft-dotnet-core-aspnet
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.6-alpine3.12 AS runtime
WORKDIR /app
COPY --from=buildtime /app/out ./
RUN apk add --no-cache \
      dumb-init
# RUN dotnet user-secrets set SendGridUser myuser && \
#     dotnet user-secrets set SendGridKey mykey
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["dotnet", "aspnetapp.dll"]
