version: '3.3'

services:
  database: # https://hub.docker.com/_/postgres
    restart: always
    image: postgres:13.2-alpine
    # For possible command-line arguments see
    # https://www.postgresql.org/docs/current/app-postgres.html
    # and for possible configuration parameters like `max_connections` see
    # https://www.postgresql.org/docs/current/runtime-config.html
    command: [
      "-c", "max_connections=100"
    ]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=postgres
    volumes:
      - data:/var/lib/postgresql/data
      - ./secrets:/run/secrets:ro

  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: ./Dockerfile-production
    # https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-5.0#command-line
    command: ["dotnet", "App.dll"]
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=production
      - XBASE_Host=https://${HOST}
      - XBASE_JsonWebToken__EncryptionCertificatePassword=${JSON_WEB_TOKEN_ENCRYPTION_CERTIFICATE_PASSWORD}
      - XBASE_JsonWebToken__SigningCertificatePassword=${JSON_WEB_TOKEN_SIGNING_CERTIFICATE_PASSWORD}
      - XBASE_TestlabSolarFacadesOpenIdConnectClientSecret=${TESTLAB_SOLAR_FACADES_OPEN_ID_CONNECT_CLIENT_SECRET}
    volumes:
      - ./secrets:/run/secrets:ro
    depends_on:
      - database

  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: ./Dockerfile-production
    command: ["yarn", "start"]
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  nginx: # https://hub.docker.com/_/nginx
    restart: always
    image: nginx:1.19.9-alpine
    command: [
      "nginx",
      "-g", "daemon off;"
      ]
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./nginx/templates/production:/etc/nginx/templates:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  data:
