# syntax=docker/dockerfile:1.21
# check=error=true
# The first line fixes the Dockerfile frontend used by BuildKit. For details
# see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

FROM busybox:1.37

RUN mkdir /tmp/build/
COPY . /tmp/build/
RUN find /tmp/build/
