# Inspired by https://mherman.org/blog/dockerizing-a-react-app/
FROM node:14.15.4-alpine3.12

ARG GROUP_ID
ARG USER_ID
ARG PROJECT_NAME

#############
# As `root` #
#############

RUN \
  apk add --no-cache \
    dumb-init \
    make

ENV HOME=/home/node
RUN \
  mkdir --parents ${HOME}/app/${PROJECT_NAME}/frontend && \
  chown node:node ${HOME}/app && \
  chown node:node ${HOME}/app/${PROJECT_NAME} && \
  chown node:node ${HOME}/app/${PROJECT_NAME}/frontend && \
  ln -s ${HOME}/app /app

#############
# As `node` #
#############
USER node
WORKDIR /app/${PROJECT_NAME}/frontend

ENV PATH=/app/${PROJECT_NAME}/frontend/node_modules/.bin:$PATH
COPY \
  --chown=node:node \
  ./${PROJECT_NAME}/frontend/package.json ./
RUN yarn install

EXPOSE 3000
ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["yarn", "start"]
