# Concise introduction to GNU Make:
# https://swcarpentry.github.io/make-novice/reference.html

include ./.env

SHELL := /usr/bin/env bash
.SHELLFLAGS := -o errexit -o errtrace -o nounset -o pipefail -c
MAKEFLAGS += --warn-undefined-variables

docker_compose = \
	docker compose \
		--file ./docker-compose.development.yaml \
		--env-file ./.env

dotenv-linter = \
	docker run \
		--rm \
		--user $(shell id --user):$(shell id --group) \
		--volume "$(shell pwd):/mnt:ro" \
		--pull "always" \
		--quiet \
		dotenvlinter/dotenv-linter:latest

COMPOSE_BAKE=true

# Taken from https://www.client9.com/self-documenting-makefiles/
help : ## Print this help
	@awk -F ':|##' '/^[^\t].+?:.*?##/ {\
		printf "\033[36m%-30s\033[0m %s\n", $$1, $$NF \
	}' $(MAKEFILE_LIST)
.PHONY : help
.DEFAULT_GOAL := help

name : ## Print value of variable `NAME`
	@echo ${NAME}
.PHONY : name

dotenv : ## Assert that all variables in `./.env.development.sample` are available in `./.env`
	${dotenv-linter} diff /mnt/.env /mnt/.env.development.sample
	${dotenv-linter} diff /mnt/frontend/.env.local /mnt/frontend/.env.local.development.sample
	${dotenv-linter} diff /mnt/.env.staging.sample /mnt/.env.production.sample
	${dotenv-linter} diff /mnt/frontend/.env.local.staging.sample /mnt/frontend/.env.local.production.sample
.PHONY : dotenv

config : ## Parse, resolve and render compose file in canonical format
	${docker_compose} config
.PHONY : config

check : ## Check build configuration
	${docker_compose} build \
		--check \
		--build-arg GROUP_ID=$(shell id --group) \
		--build-arg USER_ID=$(shell id --user)
.PHONY : check

pull : ## Pull images
	${docker_compose} pull
.PHONY : pull

# To debug errors during build add `--progress plain \` to get additional
# output.
build : dotenv check pull ## Build images
	${docker_compose} build \
		--pull \
		--build-arg GROUP_ID=$(shell id --group) \
		--build-arg USER_ID=$(shell id --user)
.PHONY : build

bake : ## Print docker-compose file equivalent bake file
	${docker_compose} build \
		--print \
		--pull
		# --no-cache
.PHONY : bake

backend-build-context : ## Show the build context configured by `./backend/.dockerignore`
	DOCKER_BUILDKIT=1 \
		docker build \
			--pull \
			--no-cache \
			--progress plain \
			--file ./Dockerfile-show-build-context \
			./backend
.PHONY : backend-build-context

frontend-build-context : ## Show the build context configured by `./frontend/.dockerignore`
	DOCKER_BUILDKIT=1 \
		docker build \
			--pull \
			--no-cache \
			--progress plain \
			--file ./Dockerfile-show-build-context \
			./frontend
.PHONY : frontend-build-context

remove : ## Remove stopped containers
	${docker_compose} rm \
		--volumes
.PHONY : remove

remove-data : ## Remove data volumes
	docker volume rm \
		${NAME}_data
.PHONY : remove-data

# TODO `docker compose up` does not support `--user`, see https://github.com/docker/compose/issues/1532
up : build ## (Re)create, and start containers
	${docker_compose} up \
		--remove-orphans \
		--wait
.PHONY : up

down : ## Stop containers and remove containers and networks created by `up`
	${docker_compose} down \
		--remove-orphans
	-rm ./frontend/queries/*.generated.ts
.PHONY : down

restart : ## Restart all stopped and running containers
	${docker_compose} restart
.PHONY : restart

restartb : ## Restart the backend container
	${docker_compose} restart backend
.PHONY : restartb

attachb : ## Attach to the backend container (to detach without stopping use `CTRL-p` followed by `CTRL-q` and otherwise `CTRL-c`)
	${docker_compose} attach backend
.PHONY : attachb

prune : ## Remove all unused containers, unused networks, unused and dangling images, and unused anonymous volumes
	docker system prune \
		--volumes
.PHONY : prune

logs : ## Follow logs
	${docker_compose} logs \
		--since=1h \
		--follow
.PHONY : logs

exec : ## Execute the one-time command `${COMMAND}` against the `${CONTAINER}` container
	${docker_compose} up \
		--remove-orphans \
		--wait \
		${CONTAINER}
	${docker_compose} exec \
		--user $(shell id --user):$(shell id --group) \
		${CONTAINER} \
		${COMMAND}
.PHONY : exec

execb : CONTAINER = backend
execb : exec ## Execute the one-time command `${COMMAND}` against the `backend` container
.PHONY : execb

execf : CONTAINER = frontend
execf : exec ## Execute the one-time command `${COMMAND}` against the `frontend` container
.PHONY : execf

run : ## Run the one-time command `${COMMAND}` against a fresh `${CONTAINER}` container
	${docker_compose} run \
		--rm \
		--user $(shell id --user):$(shell id --group) \
		${CONTAINER} \
		${COMMAND}
.PHONY : run

runb : CONTAINER = backend
runb : run ## runute the one-time command `${COMMAND}` against a fresh `backend` container
.PHONY : runb

runf : CONTAINER = frontend
runf : run ## Run the one-time command `${COMMAND}` against a fresh `frontend` container
.PHONY : runf

shellb : COMMAND = bash
shellb : runb ## Enter shell in a fresh `backend` container
.PHONY : shellb

shellf : COMMAND = bash
shellf : execf ## Enter shell in the `frontend` container
.PHONY : shellf

shellb-examples : COMMAND = bash -c "cd ./examples && bash"
shellb-examples : runb ## Enter Bourne-again shell, aka, bash, in the `backend` container
.PHONY : shellb-examples

# Executing with `--privileged` is necessary according to https://github.com/dotnet/diagnostics/blob/master/documentation/FAQ.md
traceb : ## Trace backend container with identifier `${CONTAINER_ID}`, for example, `make CONTAINER_ID=c1b82eb6e03c trace-backend`
	${docker_compose} up \
		--remove-orphans \
		--wait \
		backend
	${docker_compose} exec \
			--privileged \
			backend \
			bash -c " \
				make trace \
				"
.PHONY : traceb

shelln : ## Enter shell in the `nginx` container
	${docker_compose} up \
		--remove-orphans \
		--wait \
		nginx
	${docker_compose} exec \
		nginx \
		bash
.PHONY : shelln

shelld : CONTAINER = database
shelld : COMMAND = bash
shelld : exec ## Enter shell in the `database` container
.PHONY : shelld

list : ## List all containers with health status
	${docker_compose} ps \
		--no-trunc \
		--all
.PHONY : list

dclint = \
	docker run \
		--rm \
		--tty \
		--user $(shell id --user):$(shell id --group) \
		--volume "$(shell pwd):/app" \
		--pull "always" \
		--quiet \
		zavoloklom/dclint:latest \
		--config /app/.dclintrc

hadolint = \
	docker run \
		--rm \
		--interactive \
		--user $(shell id --user):$(shell id --group) \
		--volume ./.hadolint.yaml:/.config/.hadolint.yaml \
		--pull "always" \
		--quiet \
		hadolint/hadolint:latest \
		hadolint \
		--config /.config/.hadolint.yaml

# docker run \
# 	--workdir / \
# 	--volume ./checkmake.ini:/checkmake.ini \
# 	--volume ./Makefile.development:/Makefile.development \
# 	--volume ./Makefile.production:/Makefile.production \
# 	--volume ./backend/Makefile:/Makefile.backend \
# 	--volume ./frontend/Makefile:/Makefile.frontend \
# 	quay.io/checkmake/checkmake \
# 	/Makefile.development \
# 	/Makefile.production \
# 	/Makefile.backend \
# 	/Makefile.frontend
lint : ## Lint .env files, Docker Compose files, and Dockerfiles
	@echo Lint .env Files
	${dotenv-linter} \
		check \
		--recursive \
		--ignore-checks UnorderedKey \
		.
	@echo Lint Docker Compose Files
	${dclint} .
	@echo Lint Dockerfiles
	for dockerfile in $(shell find . -name "Dockerfile*"); do \
		echo "... $${dockerfile}" \
		${hadolint} - < $${dockerfile} ; \
	done
.PHONY : lint

fix : ## Fix .env files and Docker Compose linting violations
	@echo Fix .env Files
	${dotenv-linter} \
		fix \
		--no-backup \
		--recursive \
		--ignore-checks UnorderedKey \
		.
	@echo Fix Docker Compose Files
	${dclint} --fix .
.PHONY : fix

format : ## Format Dockerfiles
	docker run \
		--rm \
		--user $(shell id --user):$(shell id --group) \
		--volume "$(shell pwd):/pwd" \
		--pull "always" \
		--quiet \
		ghcr.io/reteps/dockerfmt:latest \
		--indent 2 \
		--newline \
		--write \
		$(shell find . -name "Dockerfile*" -printf "/pwd/%h/%f ")
.PHONY : format

diagrams-plantuml : ## Draw images from textual UML diagrams
	plantuml diagrams/plantuml/*.puml
.PHONY : diagrams-plantuml

# `diagrams-structurizr starts a server which can be accessed with a browser at localhost:9090. The diagrams can be downloaded manually from there.
diagrams-structurizr : ## Serve diagrams to browser localhost Port 9090
	docker run -it --rm -p 9090:8080 -v "$(shell pwd)/diagrams/structurizr:/usr/local/structurizr structurizr/lite"
.PHONY : diagrams-structurizr
