# Concise introduction to GNU Make:
# https://swcarpentry.github.io/make-novice/reference.html

include ./.env

SHELL := /usr/bin/env bash
.SHELLFLAGS := -o errexit -o errtrace -o nounset -o pipefail -c
MAKEFLAGS += --warn-undefined-variables

docker_compose = \
	docker compose \
		--file ./docker-compose.production.yaml \
		--env-file ./.env

dotenv-linter = \
	docker run \
		--rm \
		--user $(shell id --user):$(shell id --group) \
		--volume "$(shell pwd):/mnt:ro" \
		--pull "always" \
		--quiet \
		dotenvlinter/dotenv-linter:latest

COMPOSE_BAKE=true

# Taken from https://www.client9.com/self-documenting-makefiles/
help : ## Print this help
	@awk -F ':|##' '/^[^\t].+?:.*?##/ {\
		printf "\033[36m%-30s\033[0m %s\n", $$1, $$NF \
	}' $(MAKEFILE_LIST)
.PHONY : help
.DEFAULT_GOAL := help

name : ## Print value of variable `NAME`
	@echo ${NAME}
.PHONY : name

dotenv : ## Assert that all variables in ./.env.production.sample are available in ./.env
	${dotenv-linter} diff /mnt/.env /mnt/.env.production.sample
	${dotenv-linter} diff /mnt/frontend/.env.local /mnt/frontend/.env.local.production.sample
.PHONY : dotenv

config : ## Parse, resolve and render compose file in canonical format
	${docker_compose} config
.PHONY : config

check : ## Check build configuration
	${docker_compose} build \
		--check \
		--build-arg GROUP_ID=$(shell id --group) \
		--build-arg USER_ID=$(shell id --user)
.PHONY : check

pull : ## Pull images
	${docker_compose} pull
.PHONY : pull

# To debug errors during build add `--progress plain \` to get additional
# output.
build : dotenv check pull ## Build images
	${docker_compose} build \
		--pull \
		frontend
		# --no-cache
	${docker_compose} build \
		--pull \
		backend
		# --no-cache
.PHONY : build

bake : ## Print docker-compose file equivalent bake file
	${docker_compose} build \
		--print \
		--pull
		# --no-cache
.PHONY : bake

backend-build-context : ## Show the build context configured by `./backend/.dockerignore`
	docker build \
		--pull \
		--no-cache \
		--progress plain \
		--file ./Dockerfile-show-build-context \
		./backend
.PHONY : backend-build-context

frontend-build-context : ## Show the build context configured by `./frontend/.dockerignore`
	docker build \
		--pull \
		--no-cache \
		--progress plain \
		--file ./Dockerfile-show-build-context \
		./frontend
.PHONY : frontend-build-context

remove : ## Remove stopped containers
	${docker_compose} rm \
		--volumes
.PHONY : remove

remove-data : ## Remove data volumes
	docker volume rm \
		${NAME}_data
.PHONY : remove-data

up : dotenv ## (Re)create and start containers
	${docker_compose} up \
		--remove-orphans \
		--wait
.PHONY : up

down : ## Stop containers and remove containers and networks created by `up`
	${docker_compose} down \
		--remove-orphans
.PHONY : down

restart : ## Restart all stopped and running containers
	${docker_compose} restart
.PHONY : restart

prune : ## Remove all unused containers, unused networks, unused and dangling images, and unused anonymous volumes
	docker system prune \
		--volumes
.PHONY : prune

logs : ## Follow logs
	${docker_compose} logs \
		--since=1h \
		--follow
.PHONY : logs

exec : ## Execute the one-time command `${COMMAND}` against the `${CONTAINER}` container
	${docker_compose} up \
		--remove-orphans \
		--wait \
		${CONTAINER}
	${docker_compose} exec \
		--user $(shell id --user):$(shell id --group) \
		${CONTAINER} \
		${COMMAND}
.PHONY : exec

execb : CONTAINER = backend
execb : exec ## Execute the one-time command `${COMMAND}` against the `backend` container
.PHONY : execb

execf : CONTAINER = frontend
execf : exec ## Execute the one-time command `${COMMAND}` against the `frontend` container
.PHONY : execf

shellb : COMMAND = bash
shellb : execb ## Enter shell in a running `backend` container
.PHONY : shellb

shellf : COMMAND = bash
shellf : execf ## Enter shell in a running `frontend` container
.PHONY : shellf

shelln : ## Enter shell in the `nginx` container
	${docker_compose} up \
		--remove-orphans \
		--wait \
		nginx
	${docker_compose} exec \
		nginx \
		bash
.PHONY : shelln
.PHONY : shelln

shelld : CONTAINER = database
shelld : COMMAND = bash
shelld : exec ## Enter shell in the `database` container
.PHONY : shelld

list : ## List all containers with health status
	${docker_compose} ps \
		--no-trunc \
		--all
.PHONY : list

list-services : ## List all services specified in the docker-compose file (used by Monit as configured in the `machine` project)
	${docker_compose} config \
		--services
.PHONY : list-services
