import * as graphql from "graphql";
import { Breadcrumb, Flex, Tag, Tooltip, Tree, Typography } from "antd";
import paths from "../../paths";
import EntitySummary from "../entities/EntitySummary";
import {
  GetHttpsResourcePartialFragment,
  DataPartialFragment,
  ToTreeVertexAppliedConversionMethodPartialFragment,
} from "../../queries/data.generated";
import dayjs from "dayjs";
import InlineList from "../InlineList";
import EntityLink from "../entities/EntityLink";
import { Scalars } from "../../__generated__/graphql";
import JsonViewer from "../JsonViewer";
import { useMemo, useState } from "react";
import Copyable from "../Copyable";
import { Reference } from "../Reference";
import CodeViewer from "../CodeViewer";
import AppliedMethodViewer from "../methods/AppliedMethodViewer";
import GnuPgKeyLink from "../GnuPgKeyLink";

interface ResourceTreeNode {
  key: string;
  title: string;
  vertexId: string;
  parentId?: string;
  value: GetHttpsResourcePartialFragment;
  appliedConversionMethod?: ToTreeVertexAppliedConversionMethodPartialFragment;
  children?: ResourceTreeNode[];
}

const transformToTree = (resourceTree: DataPartialFragment["resourceTree"]) => {
  const { root, nonRootVertices } = resourceTree;
  const childrenMap = new Map<
    string,
    DataPartialFragment["resourceTree"]["nonRootVertices"][0][]
  >();
  nonRootVertices.forEach((vertex) => {
    const parentId = vertex.parentId;
    if (!childrenMap.has(parentId)) {
      childrenMap.set(parentId, []);
    }
    childrenMap.get(parentId)?.push(vertex);
  });
  const buildBranch = (
    node:
      | DataPartialFragment["resourceTree"]["nonRootVertices"][0]
      | DataPartialFragment["resourceTree"]["root"],
  ): ResourceTreeNode => {
    const children = childrenMap.get(node.vertexId) || [];
    return {
      ...node,
      key: node.vertexId,
      title: node.vertexId,
      // node.value.locator || node.value.description || `ID: ${node.vertexId}`,
      children: children.map((child) => buildBranch(child)),
    };
  };
  return buildBranch(root);
};

const getBreadcrumbItems = (
  selectedId: string,
  flatNodes: (
    | DataPartialFragment["resourceTree"]["nonRootVertices"][0]
    | DataPartialFragment["resourceTree"]["root"]
  )[],
) => {
  const path = [];
  let currentId = selectedId;
  while (currentId) {
    const node = flatNodes.find((node) => node.vertexId === currentId);
    if (!node) break;
    path.unshift({
      title: `${node.value.dataFormat?.name ?? node.value.dataFormatId} (${node.vertexId})`,
    });
    if (node.__typename === "GetHttpsResourceTreeNonRootVertex") {
      currentId = node.parentId;
    } else {
      break;
    }
  }
  return path;
};

const nameFallback = (id: Scalars["Uuid"]["output"]) => ({
  uuid: id,
  name: id,
});

export default function DataSummary({
  entity,
  children,
}: {
  entity: DataPartialFragment;
  children?: React.ReactNode;
}) {
  const rootResource = useMemo(
    () => transformToTree(entity.resourceTree),
    [entity],
  );
  const [selectedResource, setSelectedResource] = useState(rootResource);
  const resourceNodes = [
    entity.resourceTree.root,
    ...entity.resourceTree.nonRootVertices,
  ];

  return (
    <EntitySummary
      entity={entity}
      route={(id) => paths.opticalData(entity.database?.uuid, id)}
      tags={[
        <Tag key="updatedAt" style={{ fontWeight: "normal" }}>
          <Tooltip title={`Updated At ${entity.timestamp}`}>
            Updated At &ldquo;{dayjs(entity.timestamp).format("DD/MM/YYYY")}
            &rdquo;
          </Tooltip>
        </Tag>,
        <Tag key="createdAt" style={{ fontWeight: "normal" }}>
          <Tooltip title={`Created At ${entity.createdAt}`}>
            Created At &ldquo;{dayjs(entity.createdAt).format("DD/MM/YYYY")}
            &rdquo;
          </Tooltip>
        </Tag>,
        <Tag key="locale" style={{ fontWeight: "normal" }}>
          Locale &ldquo;<Tooltip title="Locale">{entity.locale}</Tooltip>&rdquo;
        </Tag>,
      ]}
    >
      <div>
        Data for component{" "}
        {entity.component && (
          <EntityLink
            entity={entity.component ?? nameFallback(entity.componentId)}
            route={paths.component}
          />
        )}{" "}
        created by{" "}
        <EntityLink
          entity={entity.creator ?? nameFallback(entity.creatorId)}
          route={paths.institution}
        />{" "}
        and stored in the{" "}
        <EntityLink
          entity={entity.database ?? nameFallback(entity.databaseId)}
          route={paths.database}
        />
      </div>
      <div>
        Generated by applying the method{" "}
        <AppliedMethodViewer value={entity.appliedMethod} />
      </div>
      {children && <div>{children}</div>}
      {rootResource.children && rootResource.children.length > 0 && (
        <Tree
          showLine
          treeData={[rootResource]}
          onSelect={(_, info) => setSelectedResource(info.node)}
        />
      )}
      {selectedResource && (
        <div>
          {resourceNodes.length > 1 && (
            <Breadcrumb
              items={getBreadcrumbItems(
                selectedResource.vertexId,
                resourceNodes,
              )}
            />
          )}
          {selectedResource.value.description && (
            <div>{selectedResource.value.description}</div>
          )}
          <div>
            Located at{" "}
            <Copyable onlyIcon text={selectedResource.value.locator}>
              <Typography.Link
                href={selectedResource.value.locator}
                target="_blank"
              >
                {selectedResource.value.locator}
              </Typography.Link>
            </Copyable>
          </div>
          <div>
            Having the{" "}
            <Typography.Link
              href="https://csrc.nist.gov/pubs/fips/180-4/upd1/final"
              target="_blank"
            >
              SHA-256
            </Typography.Link>{" "}
            hash value{" "}
            <CodeViewer inline code={selectedResource.value.hashValue} /> as
            unique digital fingerprint. Use it after downloading the data to
            ensure that it has not been tampered with or gotten corrupted.
          </div>
          <div>
            Being of the data format{" "}
            <EntityLink
              entity={
                selectedResource.value.dataFormat ??
                nameFallback(selectedResource.value.dataFormatId)
              }
              route={paths.dataFormat}
            />
            {selectedResource.value.archivedFilesMetaInformation?.length >
              0 && (
              <>
                It is an archive format and the archive file contains the files{" "}
                <InlineList
                  items={selectedResource.value.archivedFilesMetaInformation}
                  renderItem={(item) => (
                    <span>
                      ./{item.path.join("/")}=
                      <EntityLink
                        entity={
                          item.dataFormat ?? nameFallback(item.dataFormatId)
                        }
                        route={paths.dataFormat}
                      />
                    </span>
                  )}
                />
              </>
            )}
          </div>
          {selectedResource.appliedConversionMethod && (
            <div>
              Generated by applying the conversion method{" "}
              <AppliedMethodViewer
                value={selectedResource.appliedConversionMethod}
              />
            </div>
          )}
        </div>
      )}
      {entity.approvals.length > 0 && (
        <Flex gap="small">
          {entity.approvals.map((approval) => (
            <div>
              The institution{" "}
              <EntityLink
                entity={approval.approver ?? nameFallback(approval.approverId)}
                route={paths.institution}
              />{" "}
              approved on {dayjs(approval.timestamp).format("DD/MM/YYYY")} that
              the data satisfies the statement given by the reference
              <Reference data={approval.statement} />
              This is proven by the GnuPG signature
              <CodeViewer code={approval.signature} />
              generated with the institution's GnuPG key{" "}
              <GnuPgKeyLink fingerprint={approval.keyFingerprint} /> of the
              message
              <CodeViewer code={approval.message} />
              The message contains the statement and the response of the query
              <CodeViewer code={graphql.print(graphql.parse(approval.query))} />
              with the variables
              <JsonViewer data={approval.variables} />
              against the GraphQL endpoint of the database{" "}
              <EntityLink
                entity={entity.database ?? nameFallback(entity.databaseId)}
                route={paths.database}
              />
              {entity.database?.locator && (
                <>
                  {" "}
                  located at{" "}
                  <Typography.Link href={entity.database.locator}>
                    {entity.database.locator}
                  </Typography.Link>
                </>
              )}
              .
            </div>
          ))}
        </Flex>
      )}
      {entity.warnings.length > 0 && (
        <div>
          Beware of{" "}
          <InlineList
            items={entity.warnings}
            renderItem={(item) => <span>&ldquo;{item}&rdquo;</span>}
          />
        </div>
      )}
    </EntitySummary>
  );
}
