# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:5.0.302-buster-slim-amd64

ARG GROUP_ID
ARG USER_ID

# Create non-root user to run commands in (see https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)
RUN \
  addgroup --system --gid ${GROUP_ID} us && \
  adduser --system --uid ${USER_ID} --ingroup us me

USER me
WORKDIR /app

ENV PATH=$PATH:/home/me/.dotnet/tools
RUN \
  dotnet tool install --global \
    dotnet-script
