# syntax=docker/dockerfile:1.6
# The above line fixes the Dockerfile frontend used by BuildKit. For details
# see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-amd64

ARG GROUP_ID
ARG USER_ID

# Create non-root user to run commands in (see https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b)
RUN \
  addgroup --system --gid ${GROUP_ID} us && \
  adduser --system --uid ${USER_ID} --ingroup us me

ENV HOME=/home/me
RUN \
  mkdir --parents ${HOME} && \
  chown \
    me:us \
    ${HOME}

USER me
WORKDIR /app

RUN \
  mkdir --parents ${HOME}/.dotnet

ENV PATH=$PATH:/home/me/.dotnet/tools
RUN \
  dotnet tool install --global \
    dotnet-script
