# syntax=docker/dockerfile:1.6
# The above line fixes the Dockerfile frontend used by BuildKit. For details
# see https://github.com/moby/buildkit/blob/master/frontend/dockerfile/docs/reference.md
# Available versions are listed on https://hub.docker.com/r/docker/dockerfile

# Inspired by
# https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp
# and
# https://docs.docker.com/engine/examples/dotnetcore/

#########
# BUILD #
#########

# https://hub.docker.com/_/microsoft-dotnet-sdk
FROM mcr.microsoft.com/dotnet/sdk:8.0-bookworm-slim-amd64 AS build

RUN \
  apt-get update && \
  apt-get upgrade --assume-yes && \
  rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*

COPY ./ /app

WORKDIR /app

RUN \
  dotnet restore
# `dotnet publish` writes its output to
# [project_file_folder]/bin/[configuration]/[framework]/publish/
# as told in the description of the option `--output` on
# https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish#options
# We cannot use this option though to specify a custom folder as explained on
# https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/7.0/solution-level-output-no-longer-valid
RUN \
  dotnet publish \
    --configuration release \
    --self-contained false \
    --no-restore

###########
# RUNTIME #
###########

# https://hub.docker.com/_/microsoft-dotnet-aspnet
FROM mcr.microsoft.com/dotnet/aspnet:8.0-bookworm-slim-amd64

RUN \
  apt-get update && \
  apt-get upgrade --assume-yes && \
  apt-get install \
    --assume-yes \
    --no-install-recommends \
    curl && \
  rm \
    --recursive \
    --force \
    /var/lib/apt/lists/*

WORKDIR /app

COPY \
  --from=build \
  /app/src/bin/Release/net8.0/publish \
  ./

RUN \
  ln --symbolic ./Metabase.dll ./App.dll

# See: https://github.com/dotnet/announcements/issues/20
# Uncomment to enable globalization APIs
#ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT false
#RUN apt-get install icu-libs
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

ENV SHELL=/bin/bash
