# Inspired by https://mherman.org/blog/dockerizing-a-react-app/

FROM node:12.10.0-alpine

# Although we bind `/app/node_modules` to a named volume in `docker-compose`,
# the permissions we set here persist; by default they are `root:root`. See
# https://github.com/docker/compose/issues/3270#issuecomment-206214034
RUN mkdir -p /app/node_modules && \
    chown node:node /app && \
    chown node:node /app/node_modules

RUN apk --no-cache add \
      make

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

CMD ["npm", "run", "start:dev"]
