mutation AddComponentManufacturer($input: AddComponentManufacturerInput!) {
  addComponentManufacturer(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmComponentManufacturer(
  $input: ConfirmComponentManufacturerInput!
) {
  confirmComponentManufacturer(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveComponentManufacturer(
  $input: RemoveComponentManufacturerInput!
) {
  removeComponentManufacturer(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
