mutation AddComponentAssembly($input: AddComponentAssemblyInput!) {
  addComponentAssembly(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateComponentAssembly($input: UpdateComponentAssemblyInput!) {
  updateComponentAssembly(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveComponentAssembly($input: RemoveComponentAssemblyInput!) {
  removeComponentAssembly(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
