#import "./components.graphql"

mutation AddComponentGeneralization($input: AddComponentGeneralizationInput!) {
  addComponentGeneralization(input: $input) {
    concretizationOfEdge {
      node {
        ...ComponentPartial
      }
    }
    generalizationOfEdge {
      node {
        ...ComponentPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveComponentGeneralization(
  $input: RemoveComponentGeneralizationInput!
) {
  removeComponentGeneralization(input: $input) {
    generalComponent {
      ...ComponentPartial
    }
    concreteComponent {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
