#import "./components.graphql"

mutation AddComponentAssembly($input: AddComponentAssemblyInput!) {
  addComponentAssembly(input: $input) {
    assembledOfEdge {
      node {
        ...ComponentPartial
      }
    }
    partOfEdge {
      node {
        ...ComponentPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateComponentAssembly($input: UpdateComponentAssemblyInput!) {
  updateComponentAssembly(input: $input) {
    assembledOfEdge {
      node {
        ...ComponentPartial
      }
    }
    partOfEdge {
      node {
        ...ComponentPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveComponentAssembly($input: RemoveComponentAssemblyInput!) {
  removeComponentAssembly(input: $input) {
    assembledComponent {
      ...ComponentPartial
    }
    partComponent {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
