fragment ComponentPartial on Component {
  id
  uuid
  name
  abbreviation
  description
  categories
  availability {
    from
    to
  }
}

fragment ReferencePartial on Reference {
  ... on Standard {
    abstract
    section
    title
    locator
    numeration {
      mainNumber
      prefix
      suffix
    }
    standardizers
    year
  }
  ... on Publication {
    abstract
    section
    title
    arXiv
    authors
    doi
    urn
    webAddress
  }
}

query Components {
  components(first: 2147483646) {
    edges {
      node {
        ...ComponentPartial
      }
    }
  }
}

query Component($uuid: Uuid!) {
  component(uuid: $uuid) {
    id
    uuid
    name
    abbreviation
    description
    categories
    extras
    availability {
      from
      to
    }
    prime {
      surface {
        description
        reference {
          ...ReferencePartial
        }
      }
      direction {
        description
        reference {
          ...ReferencePartial
        }
      }
    }
    switchableLayers {
      description
      reference {
        ...ReferencePartial
      }
    }
    manufacturers(pending: false) {
      edges {
        node {
          id
          uuid
          name
          description
        }
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    pendingManufacturers: manufacturers(pending: true) {
      edges {
        node {
          id
          uuid
          name
        }
        canCurrentUserRemoveEdge
      }
    }
    assembledOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        index
        primeSurface
        canCurrentUserUpdateEdge
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    partOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        index
        primeSurface
        canCurrentUserUpdateEdge
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    concretizationOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    generalizationOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    variantOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        canCurrentUserRemoveEdge
      }
      canCurrentUserAddEdge
    }
    canCurrentUserUpdateNode
  }
}

mutation CreateComponent(
  $name: String!
  $abbreviation: String
  $description: String!
  $categories: [ComponentCategory!]!
  $availability: OpenEndedDateTimeRangeInput
  $primeSurface: DescriptionOrReferenceInput
  $primeDirection: DescriptionOrReferenceInput
  $switchableLayers: DescriptionOrReferenceInput
  $manufacturerId: Uuid!
) {
  createComponent(
    input: {
      name: $name
      abbreviation: $abbreviation
      description: $description
      categories: $categories
      availability: $availability
      primeSurface: $primeSurface
      primeDirection: $primeDirection
      switchableLayers: $switchableLayers
      manufacturerId: $manufacturerId
    }
  ) {
    component {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateComponent(
  $componentId: Uuid!
  $name: String!
  $abbreviation: String
  $description: String!
  $categories: [ComponentCategory!]!
  $availability: OpenEndedDateTimeRangeInput
  $primeSurface: DescriptionOrReferenceInput
  $primeDirection: DescriptionOrReferenceInput
  $switchableLayers: DescriptionOrReferenceInput
) {
  updateComponent(
    input: {
      componentId: $componentId
      name: $name
      abbreviation: $abbreviation
      description: $description
      categories: $categories
      availability: $availability
      primeSurface: $primeSurface
      primeDirection: $primeDirection
      switchableLayers: $switchableLayers
    }
  ) {
    component {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
