import type * as Types from '../__generated__/graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AddComponentAssemblyMutationVariables = Types.Exact<{
  assembledComponentId: Types.Scalars['Uuid']['input'];
  partComponentId: Types.Scalars['Uuid']['input'];
  index?: Types.InputMaybe<Types.Scalars['Byte']['input']>;
  primeSurface?: Types.InputMaybe<Types.PrimeSurface>;
}>;


export type AddComponentAssemblyMutation = { addComponentAssembly: { __typename: 'AddComponentAssemblyPayload', errors: Array<{ __typename: 'AddComponentAssemblyError', code: Types.AddComponentAssemblyErrorCode, message: string, path: Array<string> }> | null } };

export type UpdateComponentAssemblyMutationVariables = Types.Exact<{
  assembledComponentId: Types.Scalars['Uuid']['input'];
  partComponentId: Types.Scalars['Uuid']['input'];
  index?: Types.InputMaybe<Types.Scalars['Byte']['input']>;
  primeSurface?: Types.InputMaybe<Types.PrimeSurface>;
}>;


export type UpdateComponentAssemblyMutation = { updateComponentAssembly: { __typename: 'UpdateComponentAssemblyPayload', errors: Array<{ __typename: 'UpdateComponentAssemblyError', code: Types.UpdateComponentAssemblyErrorCode, message: string, path: Array<string> }> | null } };

export type RemoveComponentAssemblyMutationVariables = Types.Exact<{
  assembledComponentId: Types.Scalars['Uuid']['input'];
  partComponentId: Types.Scalars['Uuid']['input'];
}>;


export type RemoveComponentAssemblyMutation = { removeComponentAssembly: { __typename: 'RemoveComponentAssemblyPayload', errors: Array<{ __typename: 'RemoveComponentAssemblyError', code: Types.RemoveComponentAssemblyErrorCode, message: string, path: Array<string> }> | null } };


export const AddComponentAssemblyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddComponentAssembly"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"index"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Byte"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"primeSurface"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"PrimeSurface"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addComponentAssembly"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"assembledComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"partComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"index"},"value":{"kind":"Variable","name":{"kind":"Name","value":"index"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"primeSurface"},"value":{"kind":"Variable","name":{"kind":"Name","value":"primeSurface"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<AddComponentAssemblyMutation, AddComponentAssemblyMutationVariables>;
export const UpdateComponentAssemblyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"UpdateComponentAssembly"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"index"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"Byte"}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"primeSurface"}},"type":{"kind":"NamedType","name":{"kind":"Name","value":"PrimeSurface"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"updateComponentAssembly"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"assembledComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"partComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"index"},"value":{"kind":"Variable","name":{"kind":"Name","value":"index"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"primeSurface"},"value":{"kind":"Variable","name":{"kind":"Name","value":"primeSurface"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<UpdateComponentAssemblyMutation, UpdateComponentAssemblyMutationVariables>;
export const RemoveComponentAssemblyDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RemoveComponentAssembly"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"removeComponentAssembly"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"assembledComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"assembledComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"partComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"partComponentId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<RemoveComponentAssemblyMutation, RemoveComponentAssemblyMutationVariables>;