import type * as Types from '../__generated__/graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AddComponentVariantMutationVariables = Types.Exact<{
  oneComponentId: Types.Scalars['Uuid']['input'];
  otherComponentId: Types.Scalars['Uuid']['input'];
}>;


export type AddComponentVariantMutation = { addComponentVariant: { __typename: 'AddComponentVariantPayload', errors: Array<{ __typename: 'AddComponentVariantError', code: Types.AddComponentVariantErrorCode, message: string, path: Array<string> }> | null } };

export type RemoveComponentVariantMutationVariables = Types.Exact<{
  oneComponentId: Types.Scalars['Uuid']['input'];
  otherComponentId: Types.Scalars['Uuid']['input'];
}>;


export type RemoveComponentVariantMutation = { removeComponentVariant: { __typename: 'RemoveComponentVariantPayload', errors: Array<{ __typename: 'RemoveComponentVariantError', code: Types.RemoveComponentVariantErrorCode, message: string, path: Array<string> }> | null } };


export const AddComponentVariantDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddComponentVariant"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"oneComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"otherComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addComponentVariant"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"oneComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"oneComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"otherComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"otherComponentId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<AddComponentVariantMutation, AddComponentVariantMutationVariables>;
export const RemoveComponentVariantDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RemoveComponentVariant"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"oneComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"otherComponentId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"removeComponentVariant"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"oneComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"oneComponentId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"otherComponentId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"otherComponentId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<RemoveComponentVariantMutation, RemoveComponentVariantMutationVariables>;