#import "./common.graphql"
#import "./institution.graphql"

fragment ComponentsPartial on Component {
  id
  uuid
  name
  abbreviation
  description
  categories
  availability {
    from
    to
  }
  prime {
    surface {
      ...DescriptionOrReferencePartial
    }
    direction {
      ...DescriptionOrReferencePartial
    }
  }
  switchableLayers {
    ...DescriptionOrReferencePartial
  }
  manufacturers {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

fragment ComponentPartial on Component {
  ...ComponentsPartial
  extras
  manager {
    node {
      uuid
      name
    }
  }
  manufacturers {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  pendingManufacturers {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      isAuthorizedToRemoveEdge
    }
  }
  assembledOf {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      index
      primeSurface
      isAuthorizedToUpdateEdge
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  partOf {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      index
      primeSurface
      isAuthorizedToUpdateEdge
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  concretizationOf {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  generalizationOf {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  variantOf {
    totalCount
    edges {
      node {
        id
        uuid
        name
        description
      }
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  isAuthorizedToUpdateNode
}

fragment ComponentDataTotalCountsPartial on Component {
  allCalorimetricData {
    totalCount
  }
  allGeometricData {
    totalCount
  }
  allHygrothermalData {
    totalCount
  }
  allLifeCycleData {
    totalCount
  }
  allOpticalData {
    totalCount
  }
  allPhotovoltaicData {
    totalCount
  }
}

query ComponentNames(
  $first: Int!
  $after: String
  $where: ComponentFilterInput
  $order: [ComponentSortInput!]
) {
  connection: components(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query Components(
  $first: Int!
  $after: String
  $where: ComponentFilterInput
  $order: [ComponentSortInput!]
) {
  connection: components(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...ComponentsPartial
      }
    }
  }
}

query Component($id: Uuid!) {
  component(id: $id) {
    ...ComponentPartial
  }
}

query ComponentDataTotalCounts($id: Uuid!) {
  component(id: $id) {
    ...ComponentDataTotalCountsPartial
  }
}

mutation CreateComponent($input: CreateComponentInput!) {
  createComponent(input: $input) {
    component {
      ...ComponentPartial
      manager {
        node {
          ...InstitutionPartial
        }
      }
      manufacturers {
        edges {
          node {
            ...InstitutionPartial
          }
        }
      }
      pendingManufacturers {
        edges {
          node {
            ...InstitutionPartial
          }
        }
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateComponent($input: UpdateComponentInput!) {
  updateComponent(input: $input) {
    component {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
