fragment ComponentPartial on Component {
  id
  uuid
  name
  abbreviation
  description
  categories
  availability {
    from
    to
  }
}

fragment ReferencePartial on Reference {
  ... on Standard {
    abstract
    section
    title
    locator
    numeration {
      mainNumber
      prefix
      suffix
    }
    standardizers
    year
  }
  ... on Publication {
    abstract
    section
    title
    arXiv
    authors
    doi
    urn
    webAddress
  }
}

query ComponentNames {
  components(first: 2147483646) {
    edges {
      node {
        uuid
        name
      }
    }
  }
}

query Components {
  components(first: 2147483646) {
    edges {
      node {
        ...ComponentPartial
      }
    }
  }
}

query Component($uuid: Uuid!) {
  component(id: $uuid) {
    id
    uuid
    name
    abbreviation
    description
    categories
    extras
    availability {
      from
      to
    }
    manager {
      node {
        uuid
        name
      }
    }
    prime {
      surface {
        description
        reference {
          ...ReferencePartial
        }
      }
      direction {
        description
        reference {
          ...ReferencePartial
        }
      }
    }
    switchableLayers {
      description
      reference {
        ...ReferencePartial
      }
    }
    manufacturers {
      edges {
        node {
          id
          uuid
          name
          description
        }
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    pendingManufacturers {
      edges {
        node {
          id
          uuid
          name
        }
        isAuthorizedToRemoveEdge
      }
    }
    assembledOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        index
        primeSurface
        isAuthorizedToUpdateEdge
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    partOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        index
        primeSurface
        isAuthorizedToUpdateEdge
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    concretizationOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    generalizationOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    variantOf {
      edges {
        node {
          id
          uuid
          name
          description
        }
        isAuthorizedToRemoveEdge
      }
      isAuthorizedToAddEdge
    }
    isAuthorizedToUpdateNode
  }
}

mutation CreateComponent($input: CreateComponentInput!) {
  createComponent(input: $input) {
    component {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateComponent($input: UpdateComponentInput!) {
  updateComponent(input: $input) {
    component {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
