#import "./components.graphql"

mutation AddComponentVariant($input: AddComponentVariantInput!) {
  addComponentVariant(input: $input) {
    variantOfEdge {
      node {
        ...ComponentPartial
      }
    }
    reverseVariantOfEdge {
      node {
        ...ComponentPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveComponentVariant($input: RemoveComponentVariantInput!) {
  removeComponentVariant(input: $input) {
    oneComponent {
      ...ComponentPartial
    }
    otherComponent {
      ...ComponentPartial
    }
    errors {
      code
      message
      path
    }
  }
}
