fragment CurrentUserPartial on User {
  id
  uuid
  name
  email
  hasPassword
  isEmailConfirmed
  phoneNumber
  roles
  isAuthorizedToManageOpenIdConnect
  representedInstitutions {
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query CurrentUser {
  currentUser {
    ...CurrentUserPartial
  }
}

mutation LoginUser($input: LoginUserInput!) {
  loginUser(input: $input) {
    requiresTwoFactor
    user {
      ...CurrentUserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation LoginUserWithTwoFactorCode($input: LoginUserWithTwoFactorCodeInput!) {
  loginUserWithTwoFactorCode(input: $input) {
    user {
      ...CurrentUserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation LoginUserWithRecoveryCode($input: LoginUserWithRecoveryCodeInput!) {
  loginUserWithRecoveryCode(input: $input) {
    user {
      ...CurrentUserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation LogoutUser {
  logoutUser {
    errors {
      code
      message
      path
    }
  }
}

mutation ChangeUserEmail($input: ChangeUserEmailInput!) {
  changeUserEmail(input: $input) {
    user {
      ...CurrentUserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

query TwoFactorAuthentication {
  currentUser {
    twoFactorAuthentication {
      hasAuthenticator
      isEnabled
      isMachineRemembered
      recoveryCodesLeftCount
    }
  }
}

mutation GenerateUserTwoFactorRecoveryCodes {
  generateUserTwoFactorRecoveryCodes {
    twoFactorRecoveryCodes
    errors {
      code
      message
      path
    }
  }
}

mutation DisableUserTwoFactorAuthentication {
  disableUserTwoFactorAuthentication {
    errors {
      code
      message
      path
    }
  }
}

mutation ForgetUserTwoFactorAuthenticationClient {
  forgetUserTwoFactorAuthenticationClient {
    errors {
      code
      message
      path
    }
  }
}

mutation ResetUserTwoFactorAuthenticator {
  resetUserTwoFactorAuthenticator {
    errors {
      code
      message
      path
    }
  }
}

mutation GenerateUserTwoFactorAuthenticatorSharedKeyAndQrCodeUri {
  generateUserTwoFactorAuthenticatorSharedKeyAndQrCodeUri {
    sharedKey
    authenticatorUri
    errors {
      code
      message
      path
    }
  }
}

mutation EnableUserTwoFactorAuthenticator($verificationCode: String!) {
  enableUserTwoFactorAuthenticator(
    input: { verificationCode: $verificationCode }
  ) {
    twoFactorRecoveryCodes
    sharedKey
    authenticatorUri
    errors {
      code
      message
      path
    }
  }
}

mutation ChangeUserPassword($input: ChangeUserPasswordInput!) {
  changeUserPassword(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation SetUserPassword($input: SetUserPasswordInput!) {
  setUserPassword(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeletePersonalUserData($input: DeletePersonalUserDataInput!) {
  deletePersonalUserData(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ResendUserEmailVerification {
  resendUserEmailVerification {
    errors {
      code
      message
      path
    }
  }
}

mutation SetUserPhoneNumber($input: SetUserPhoneNumberInput!) {
  setUserPhoneNumber(input: $input) {
    user {
      ...CurrentUserPartial
    }
    errors {
      code
      message
      path
    }
  }
}
