fragment DataFormatsPartial on DataFormat {
  id
  uuid
  name
  extension
  description
  mediaType
  schemaLocator
  reference {
    ... on Standard {
      abstract
      section
      title
      locator
      numeration {
        mainNumber
        prefix
        suffix
      }
      standardizers
      year
    }
    ... on Publication {
      abstract
      section
      title
      arXiv
      authors
      doi
      urn
      webAddress
    }
  }
}

fragment DataFormatPartial on DataFormat {
  ...DataFormatsPartial
  isAuthorizedToUpdateNode
  manager {
    node {
      id
      uuid
      name
    }
  }
}

query DataFormats {
  dataFormats {
    edges {
      node {
        ...DataFormatsPartial
      }
    }
  }
}

query DataFormat($uuid: Uuid!) {
  dataFormat(id: $uuid) {
    ...DataFormatPartial
  }
}

mutation CreateDataFormat($input: CreateDataFormatInput!) {
  createDataFormat(input: $input) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateDataFormat($input: UpdateDataFormatInput!) {
  updateDataFormat(input: $input) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}
