fragment DatabasePartial on Database {
  id
  uuid
  name
  description
  locator
  operator {
    node {
      uuid
      name
    }
  }
  verificationState
  verificationCode
}

query Databases {
  databases {
    edges {
      node {
        ...DatabasePartial
      }
    }
  }
}

query PendingDatabases {
  pendingDatabases {
    edges {
      node {
        ...DatabasePartial
        isAuthorizedToVerifyNode
      }
    }
  }
}

query Database($uuid: Uuid!) {
  database(id: $uuid) {
    ...DatabasePartial
    isAuthorizedToUpdateNode
    isAuthorizedToVerifyNode
  }
}

mutation CreateDatabase($input: CreateDatabaseInput!) {
  createDatabase(input: $input) {
    database {
      ...DatabasePartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateDatabase($input: UpdateDatabaseInput!) {
  updateDatabase(input: $input) {
    database {
      ...DatabasePartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation VerifyDatabase($input: VerifyDatabaseInput!) {
  verifyDatabase(input: $input) {
    database {
      ...DatabasePartial
    }
    errors {
      code
      message
      path
    }
  }
}
