#import "./common.graphql"

fragment DataFormatsPartial on DataFormat {
  id
  uuid
  name
  extension
  description
  mediaType
  schemaLocator
  reference {
    ...ReferencePartial
  }
}

fragment DataFormatPartial on DataFormat {
  ...DataFormatsPartial
  isAuthorizedToUpdateNode
  manager {
    node {
      id
      uuid
      name
    }
  }
}

query DataFormatNames(
  $first: Int!
  $after: String
  $where: DataFormatFilterInput
  $order: [DataFormatSortInput!]
) {
  connection: dataFormats(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query DataFormats(
  $first: Int!
  $after: String
  $where: DataFormatFilterInput
  $order: [DataFormatSortInput!]
) {
  connection: dataFormats(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...DataFormatsPartial
      }
    }
  }
}

query DataFormat($uuid: Uuid!) {
  dataFormat(id: $uuid) {
    ...DataFormatPartial
  }
}

mutation CreateDataFormat($input: CreateDataFormatInput!) {
  createDataFormat(input: $input) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateDataFormat($input: UpdateDataFormatInput!) {
  updateDataFormat(input: $input) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}
