fragment DatabasesPartial on Database {
  id
  uuid
  name
  description
  locator
  operator {
    node {
      uuid
      name
    }
  }
  verificationState
  verificationCode
}

fragment PendingDatabasesPartial on Database {
  ...DatabasesPartial
  isAuthorizedToVerifyNode
}

fragment DatabasePartial on Database {
  ...DatabasesPartial
  isAuthorizedToUpdateNode
  isAuthorizedToVerifyNode
}

query DatabaseNames(
  $first: Int!
  $after: String
  $where: DatabaseFilterInput
  $order: [DatabaseSortInput!]
) {
  connection: databases(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query Databases(
  $first: Int!
  $after: String
  $where: DatabaseFilterInput
  $order: [DatabaseSortInput!]
) {
  connection: databases(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...DatabasesPartial
      }
    }
  }
}

query PendingDatabases {
  pendingDatabases {
    edges {
      node {
        ...PendingDatabasesPartial
      }
    }
  }
}

query Database($uuid: Uuid!) {
  database(id: $uuid) {
    ...DatabasePartial
  }
}

mutation CreateDatabase($input: CreateDatabaseInput!) {
  createDatabase(input: $input) {
    database {
      ...DatabasePartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateDatabase($input: UpdateDatabaseInput!) {
  updateDatabase(input: $input) {
    database {
      ...DatabasePartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation VerifyDatabase($input: VerifyDatabaseInput!) {
  verifyDatabase(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
