fragment DataFormatPartial on DataFormat {
  id
  uuid
  name
  extension
  description
  mediaType
  schemaLocator
  reference {
    ... on Standard {
      abstract
      section
      title
      locator
      numeration {
        mainNumber
        prefix
        suffix
      }
      standardizers
      year
    }
    ... on Publication {
      abstract
      section
      title
      arXiv
      authors
      doi
      urn
      webAddress
    }
  }
  manager {
    node {
      id
      uuid
      name
    }
  }
}

query DataFormats {
  dataFormats {
    edges {
      node {
        ...DataFormatPartial
      }
    }
  }
}

query DataFormat($uuid: Uuid!) {
  dataFormat(id: $uuid) {
    ...DataFormatPartial
    isAuthorizedToUpdateNode
  }
}

mutation CreateDataFormat(
  $name: String!
  $extension: String
  $description: String!
  $mediaType: String!
  $schemaLocator: Url
  $reference: ReferenceInput
  $managerId: Uuid!
) {
  createDataFormat(
    input: {
      name: $name
      extension: $extension
      description: $description
      mediaType: $mediaType
      schemaLocator: $schemaLocator
      reference: $reference
      managerId: $managerId
    }
  ) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateDataFormat(
  $dataFormatId: Uuid!
  $name: String!
  $extension: String
  $description: String!
  $mediaType: String!
  $schemaLocator: Url
  $reference: ReferenceInput
) {
  updateDataFormat(
    input: {
      dataFormatId: $dataFormatId
      name: $name
      extension: $extension
      description: $description
      mediaType: $mediaType
      schemaLocator: $schemaLocator
      reference: $reference
    }
  ) {
    dataFormat {
      ...DataFormatPartial
    }
    errors {
      code
      message
      path
    }
  }
}
