fragment GnuPgKeyFingerprintPartial on GnuPgKeyFingerprint {
  fingerprint
  allowedAt
  forbiddenAt
  isAllowed
  isForbidden
  user {
    node {
      uuid
      name
    }
  }
  canCurrentUserAllowNode
  canCurrentUserForbidNode
}

mutation AddGnuPgKeyFingerprint(
  $fingerprint: String!
  $institutionId: Uuid!
) {
  addGnuPgKeyFingerprint(
    input: {
      fingerprint: $fingerprint
      institutionId: $institutionId
    }
  ) {
    gnuPgKeyFingerprint {
      ...GnuPgKeyFingerprintPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation AllowGnuPgKeyFingerprint($fingerprint: String!) {
  allowGnuPgKeyFingerprint(input: { fingerprint: $fingerprint }) {
    gnuPgKeyFingerprint {
      ...GnuPgKeyFingerprintPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ForbidGnuPgKeyFingerprint($fingerprint: String!) {
  revokeGnuPgKeyFingerprint(input: { fingerprint: $fingerprint }) {
    gnuPgKeyFingerprint {
      ...GnuPgKeyFingerprintPartial
    }
    errors {
      code
      message
      path
    }
  }
}
