import type * as Types from '../__generated__/graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GnuPgKeyFingerprintPartialFragment = { __typename: 'GnuPgKeyFingerprint', fingerprint: string, allowedAt: Date | null, forbiddenAt: Date | null, isAuthorizedToAllowNode: boolean, isAuthorizedToForbidNode: boolean, user: { __typename: 'GnuPgKeyFingerprintUserEdge', node: { __typename: 'User', uuid: string, name: string } } };

export type AddGnuPgKeyFingerprintMutationVariables = Types.Exact<{
  institutionId: Types.Scalars['Uuid']['input'];
  fingerprint: Types.Scalars['String']['input'];
}>;


export type AddGnuPgKeyFingerprintMutation = { addGnuPgKeyFingerprint: { __typename: 'AddGnuPgKeyFingerprintPayload', gnuPgKeyFingerprint: { __typename: 'GnuPgKeyFingerprint', fingerprint: string, allowedAt: Date | null, forbiddenAt: Date | null, isAuthorizedToAllowNode: boolean, isAuthorizedToForbidNode: boolean, user: { __typename: 'GnuPgKeyFingerprintUserEdge', node: { __typename: 'User', uuid: string, name: string } } } | null, errors: Array<{ __typename: 'AddGnuPgKeyFingerprintError', code: Types.AddGnuPgKeyFingerprintErrorCode, message: string, path: Array<string> }> | null } };

export type AllowGnuPgKeyFingerprintMutationVariables = Types.Exact<{
  fingerprint: Types.Scalars['String']['input'];
}>;


export type AllowGnuPgKeyFingerprintMutation = { allowGnuPgKeyFingerprint: { __typename: 'AllowGnuPgKeyFingerprintPayload', gnuPgKeyFingerprint: { __typename: 'GnuPgKeyFingerprint', fingerprint: string, allowedAt: Date | null, forbiddenAt: Date | null, isAuthorizedToAllowNode: boolean, isAuthorizedToForbidNode: boolean, user: { __typename: 'GnuPgKeyFingerprintUserEdge', node: { __typename: 'User', uuid: string, name: string } } } | null, errors: Array<{ __typename: 'AllowGnuPgKeyFingerprintError', code: Types.AllowGnuPgKeyFingerprintErrorCode, message: string, path: Array<string> }> | null } };

export type ForbidGnuPgKeyFingerprintMutationVariables = Types.Exact<{
  fingerprint: Types.Scalars['String']['input'];
}>;


export type ForbidGnuPgKeyFingerprintMutation = { forbidGnuPgKeyFingerprint: { __typename: 'ForbidGnuPgKeyFingerprintPayload', gnuPgKeyFingerprint: { __typename: 'GnuPgKeyFingerprint', fingerprint: string, allowedAt: Date | null, forbiddenAt: Date | null, isAuthorizedToAllowNode: boolean, isAuthorizedToForbidNode: boolean, user: { __typename: 'GnuPgKeyFingerprintUserEdge', node: { __typename: 'User', uuid: string, name: string } } } | null, errors: Array<{ __typename: 'ForbidGnuPgKeyFingerprintError', code: Types.ForbidGnuPgKeyFingerprintErrorCode, message: string, path: Array<string> }> | null } };

export const GnuPgKeyFingerprintPartialFragmentDoc = {"kind":"Document","definitions":[{"kind":"FragmentDefinition","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"GnuPgKeyFingerprint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fingerprint"}},{"kind":"Field","name":{"kind":"Name","value":"allowedAt"}},{"kind":"Field","name":{"kind":"Name","value":"forbiddenAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uuid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToAllowNode"}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToForbidNode"}}]}}]} as unknown as DocumentNode<GnuPgKeyFingerprintPartialFragment, unknown>;
export const AddGnuPgKeyFingerprintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddGnuPgKeyFingerprint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addGnuPgKeyFingerprint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"institutionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"fingerprint"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"gnuPgKeyFingerprint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"GnuPgKeyFingerprint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fingerprint"}},{"kind":"Field","name":{"kind":"Name","value":"allowedAt"}},{"kind":"Field","name":{"kind":"Name","value":"forbiddenAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uuid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToAllowNode"}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToForbidNode"}}]}}]} as unknown as DocumentNode<AddGnuPgKeyFingerprintMutation, AddGnuPgKeyFingerprintMutationVariables>;
export const AllowGnuPgKeyFingerprintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AllowGnuPgKeyFingerprint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"allowGnuPgKeyFingerprint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"fingerprint"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"gnuPgKeyFingerprint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"GnuPgKeyFingerprint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fingerprint"}},{"kind":"Field","name":{"kind":"Name","value":"allowedAt"}},{"kind":"Field","name":{"kind":"Name","value":"forbiddenAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uuid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToAllowNode"}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToForbidNode"}}]}}]} as unknown as DocumentNode<AllowGnuPgKeyFingerprintMutation, AllowGnuPgKeyFingerprintMutationVariables>;
export const ForbidGnuPgKeyFingerprintDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ForbidGnuPgKeyFingerprint"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"String"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"forbidGnuPgKeyFingerprint"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"fingerprint"},"value":{"kind":"Variable","name":{"kind":"Name","value":"fingerprint"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"gnuPgKeyFingerprint"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"FragmentSpread","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"}}]}},{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}},{"kind":"FragmentDefinition","name":{"kind":"Name","value":"GnuPgKeyFingerprintPartial"},"typeCondition":{"kind":"NamedType","name":{"kind":"Name","value":"GnuPgKeyFingerprint"}},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"fingerprint"}},{"kind":"Field","name":{"kind":"Name","value":"allowedAt"}},{"kind":"Field","name":{"kind":"Name","value":"forbiddenAt"}},{"kind":"Field","name":{"kind":"Name","value":"user"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"node"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"uuid"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}}]}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToAllowNode"}},{"kind":"Field","name":{"kind":"Name","value":"isAuthorizedToForbidNode"}}]}}]} as unknown as DocumentNode<ForbidGnuPgKeyFingerprintMutation, ForbidGnuPgKeyFingerprintMutationVariables>;