#import "./components.graphql"
#import "./dataFormats.graphql"
#import "./databases.graphql"
#import "./gnuPgKeyFingerprints.graphql"
#import "./methods.graphql"
#import "./openIdConnect.graphql"

fragment ContactInformationPartial on ContactInformation {
  phoneNumber
  isPhoneNumberConfirmed
  postalAddress
  emailAddress
  isEmailAddressConfirmed
  websiteLocator
}

fragment InstitutionsPartial on Institution {
  id
  uuid
  name
  abbreviation
  description
}

fragment PendingInstitutionsPartial on Institution {
  id
  uuid
  name
  isAuthorizedToVerifyNode
}

fragment InstitutionPartial on Institution {
  ...InstitutionsPartial
  contact {
    ...ContactInformationPartial
  }
  state
  operatingState
  extras
  isAuthorizedToUpdateNode
  isAuthorizedToDeleteNode
  isAuthorizedToSwitchOperatingStateOfNode
  manufacturedComponents {
    totalCount
    edges {
      node {
        ...ComponentsPartial
      }
    }
  }
  managedComponents {
    totalCount
    edges {
      node {
        ...ComponentsPartial
      }
    }
    isAuthorizedToAddEdge
  }
  pendingManufacturedComponents {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
    }
    isAuthorizedToConfirmEdges
  }
  operatedDatabases {
    totalCount
    edges {
      node {
        ...DatabasesPartial
      }
    }
    isAuthorizedToAddEdge
  }
  representatives {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      role
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddEdge
  }
  pendingRepresentatives {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      role
      isAuthorizedToRemoveEdge
    }
  }
  manager {
    node {
      id
      uuid
      name
    }
  }
  managedDataFormats {
    totalCount
    edges {
      node {
        ...DataFormatsPartial
      }
    }
    isAuthorizedToAddEdge
  }
  managedMethods {
    totalCount
    edges {
      node {
        ...MethodsPartial
      }
    }
    isAuthorizedToAddEdge
  }
  developedMethods {
    totalCount
    edges {
      node {
        ...MethodsPartial
      }
    }
  }
  pendingDevelopedMethods {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
    }
    isAuthorizedToConfirmEdges
  }
  gnuPgKeyFingerprints {
    totalCount
    edges {
      node {
        ...GnuPgKeyFingerprintsPartial
      }
    }
    isAuthorizedToAddEdge
  }
  openIdConnectApplications {
    totalCount
    edges {
      node {
        ...OpenIdConnectApplicationsPartial
      }
    }
    isAuthorizedToAddEdge
  }
  managedInstitutions {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
    }
    isAuthorizedToAddEdge
  }
}

query InstitutionNames {
  institutions(first: 2147483646) {
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query Institutions {
  institutions(first: 2147483646) {
    totalCount
    edges {
      node {
        ...InstitutionsPartial
      }
    }
  }
}

query PendingInstitutions {
  pendingInstitutions {
    totalCount
    edges {
      node {
        ...PendingInstitutionsPartial
      }
    }
  }
}

mutation CreateInstitution($input: CreateInstitutionInput!) {
  createInstitution(input: $input) {
    institution {
      ...InstitutionPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateInstitution($input: UpdateInstitutionInput!) {
  updateInstitution(input: $input) {
    institution {
      ...InstitutionPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation VerifyInstitution($institutionId: Uuid!) {
  verifyInstitution(input: { institutionId: $institutionId }) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteInstitution($institutionId: Uuid!) {
  deleteInstitution(input: { institutionId: $institutionId }) {
    errors {
      code
      message
      path
    }
  }
}
mutation SwitchInstitutionOperatingState($institutionId: Uuid!) {
  switchInstitutionOperatingState(input: { institutionId: $institutionId }) {
    institution {
      id
      operatingState
    }
    errors {
      code
      message
      path
    }
  }
}

query Institution($uuid: Uuid!) {
  institution(id: $uuid) {
    ...InstitutionPartial
  }
}
