#import "./institutions.graphql"
#import "./users.graphql"

mutation AddInstitutionRepresentative(
  $input: AddInstitutionRepresentativeInput!
) {
  addInstitutionRepresentative(input: $input) {
    institutionRepresentativeEdge {
      node {
        ...UserPartial
      }
      role
    }
    representedInstitutionEdge {
      node {
        ...InstitutionPartial
      }
      role
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmInstitutionRepresentative(
  $input: ConfirmInstitutionRepresentativeInput!
) {
  confirmInstitutionRepresentative(input: $input) {
    institutionRepresentativeEdge {
      node {
        ...UserPartial
      }
      role
    }
    representedInstitutionEdge {
      node {
        ...InstitutionPartial
      }
      role
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveInstitutionRepresentative(
  $input: RemoveInstitutionRepresentativeInput!
) {
  removeInstitutionRepresentative(input: $input) {
    institution {
      ...InstitutionPartial
    }
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}
