mutation AddInstitutionMethodDeveloper(
  $input: AddInstitutionMethodDeveloperInput!
) {
  addInstitutionMethodDeveloper(
    input: $input
  ) {
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmInstitutionMethodDeveloper(
  $input: ConfirmInstitutionMethodDeveloperInput!
) {
  confirmInstitutionMethodDeveloper(
    input: $input
  ) {
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveInstitutionMethodDeveloper(
  $input: RemoveInstitutionMethodDeveloperInput!
) {
  removeInstitutionMethodDeveloper(
    input: $input
  ) {
    errors {
      code
      message
      path
    }
  }
}
