#import "./method.graphql"
#import "./institution.graphql"

mutation AddInstitutionMethodDeveloper(
  $input: AddInstitutionMethodDeveloperInput!
) {
  addInstitutionMethodDeveloper(input: $input) {
    developedMethodEdge {
      node {
        ...MethodPartial
      }
    }
    methodDeveloperEdge {
      node {
        ...InstitutionPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmInstitutionMethodDeveloper(
  $input: ConfirmInstitutionMethodDeveloperInput!
) {
  confirmInstitutionMethodDeveloper(input: $input) {
    developedMethodEdge {
      node {
        ...MethodPartial
      }
    }
    methodDeveloperEdge {
      node {
        ...InstitutionPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveInstitutionMethodDeveloper(
  $input: RemoveInstitutionMethodDeveloperInput!
) {
  removeInstitutionMethodDeveloper(input: $input) {
    method {
      ...MethodPartial
    }
    institution {
      ...InstitutionPartial
    }
    errors {
      code
      message
      path
    }
  }
}
