import type * as Types from '../__generated__/graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AddInstitutionMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  institutionId: Types.Scalars['Uuid']['input'];
}>;


export type AddInstitutionMethodDeveloperMutation = { addInstitutionMethodDeveloper: { __typename: 'AddInstitutionMethodDeveloperPayload', errors: Array<{ __typename: 'AddInstitutionMethodDeveloperError', code: Types.AddInstitutionMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };

export type ConfirmInstitutionMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  institutionId: Types.Scalars['Uuid']['input'];
}>;


export type ConfirmInstitutionMethodDeveloperMutation = { confirmInstitutionMethodDeveloper: { __typename: 'ConfirmInstitutionMethodDeveloperPayload', errors: Array<{ __typename: 'ConfirmInstitutionMethodDeveloperError', code: Types.ConfirmInstitutionMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };

export type RemoveInstitutionMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  institutionId: Types.Scalars['Uuid']['input'];
}>;


export type RemoveInstitutionMethodDeveloperMutation = { removeInstitutionMethodDeveloper: { __typename: 'RemoveInstitutionMethodDeveloperPayload', errors: Array<{ __typename: 'RemoveInstitutionMethodDeveloperError', code: Types.RemoveInstitutionMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };


export const AddInstitutionMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddInstitutionMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addInstitutionMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"institutionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<AddInstitutionMethodDeveloperMutation, AddInstitutionMethodDeveloperMutationVariables>;
export const ConfirmInstitutionMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ConfirmInstitutionMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"confirmInstitutionMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"institutionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<ConfirmInstitutionMethodDeveloperMutation, ConfirmInstitutionMethodDeveloperMutationVariables>;
export const RemoveInstitutionMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RemoveInstitutionMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"removeInstitutionMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"institutionId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"institutionId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<RemoveInstitutionMethodDeveloperMutation, RemoveInstitutionMethodDeveloperMutationVariables>;