mutation AddInstitutionRepresentative(
  $input: AddInstitutionRepresentativeInput!
) {
  addInstitutionRepresentative(input: $input) {
    institutionRepresentativeEdge {
      node {
        id
        uuid
        name
      }
      role
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveInstitutionRepresentative(
  $input: RemoveInstitutionRepresentativeInput!
) {
  removeInstitutionRepresentative(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmInstitutionRepresentative(
  $input: ConfirmInstitutionRepresentativeInput!
) {
  confirmInstitutionRepresentative(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
