fragment MethodPartial on Method {
  id
  uuid
  name
  description
  validity {
    from
    to
  }
  availability {
    from
    to
  }
  reference {
    ... on Standard {
      abstract
      section
      title
      locator
      numeration {
        mainNumber
        prefix
        suffix
      }
      standardizers
      year
    }
    ... on Publication {
      abstract
      section
      title
      arXiv
      authors
      doi
      urn
      webAddress
    }
  }
  calculationLocator
  categories
  developers {
    edges {
      node {
        ... on Institution {
          id
          uuid
          name
          description
        }
        ... on User {
          id
          uuid
          name
        }
      }
      isAuthorizedToConfirmEdge
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddInstitutionEdge
    isAuthorizedToAddUserEdge
  }
  pendingDevelopers: developers(pending: true) {
    edges {
      node {
        ... on Institution {
          id
          uuid
          name
          description
        }
        ... on User {
          id
          uuid
          name
        }
      }
      isAuthorizedToConfirmEdge
      isAuthorizedToRemoveEdge
    }
  }
  manager {
    node {
      id
      uuid
      name
    }
  }
}

query Methods {
  methods {
    edges {
      node {
        ...MethodPartial
      }
    }
  }
}

query Method($uuid: Uuid!) {
  method(id: $uuid) {
    ...MethodPartial
    isAuthorizedToUpdateNode
  }
}

mutation CreateMethod(
  $name: String!
  $description: String!
  $validity: OpenEndedDateTimeRangeInput
  $availability: OpenEndedDateTimeRangeInput
  $reference: ReferenceInput
  $calculationLocator: Url
  $categories: [MethodCategory!]!
  $managerId: Uuid!
  $institutionDeveloperIds: [Uuid!]!
  $userDeveloperIds: [Uuid!]!
) {
  createMethod(
    input: {
      name: $name
      description: $description
      validity: $validity
      availability: $availability
      reference: $reference
      calculationLocator: $calculationLocator
      categories: $categories
      managerId: $managerId
      institutionDeveloperIds: $institutionDeveloperIds
      userDeveloperIds: $userDeveloperIds
    }
  ) {
    method {
      ...MethodPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateMethod(
  $methodId: Uuid!
  $name: String!
  $description: String!
  $validity: OpenEndedDateTimeRangeInput
  $availability: OpenEndedDateTimeRangeInput
  $reference: ReferenceInput
  $calculationLocator: Url
  $categories: [MethodCategory!]!
) {
  updateMethod(
    input: {
      methodId: $methodId
      name: $name
      description: $description
      validity: $validity
      availability: $availability
      reference: $reference
      calculationLocator: $calculationLocator
      categories: $categories
    }
  ) {
    method {
      ...MethodPartial
    }
    errors {
      code
      message
      path
    }
  }
}
