#import "./common.graphql"
#import "./institution.graphql"

fragment MethodsPartial on Method {
  id
  uuid
  name
  description
  calculationLocator
  categories
  validity {
    from
    to
  }
  availability {
    from
    to
  }
  parameters {
    name
    type
  }
  sources {
    name
    description
  }
  reference {
    ...ReferencePartial
  }
  developers {
    edges {
      node {
        ... on Institution {
          id
          uuid
          name
          description
        }
        ... on User {
          id
          uuid
          name
        }
      }
    }
  }
}

fragment MethodDeveloperStakeholderPartial on Stakeholder {
  ... on Institution {
    id
    uuid
    name
    description
  }
  ... on User {
    id
    uuid
    name
  }
}

fragment MethodPartial on Method {
  ...MethodsPartial
  isAuthorizedToUpdateNode
  developers {
    edges {
      node {
        ...MethodDeveloperStakeholderPartial
      }
      isAuthorizedToConfirmEdge
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToAddInstitutionEdge
    isAuthorizedToAddUserEdge
  }
  pendingDevelopers {
    edges {
      node {
        ...MethodDeveloperStakeholderPartial
      }
      isAuthorizedToConfirmEdge
      isAuthorizedToRemoveEdge
    }
  }
  manager {
    node {
      id
      uuid
      name
    }
  }
}

query MethodNames(
  $first: Int!
  $after: String
  $where: MethodFilterInput
  $order: [MethodSortInput!]
) {
  connection: methods(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query Methods(
  $first: Int!
  $after: String
  $where: MethodFilterInput
  $order: [MethodSortInput!]
) {
  connection: methods(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...MethodsPartial
      }
    }
  }
}

query Method($id: Uuid!) {
  method(id: $id) {
    ...MethodPartial
  }
}

mutation CreateMethod($input: CreateMethodInput!) {
  createMethod(input: $input) {
    method {
      ...MethodPartial
      manager {
        node {
          ...InstitutionPartial
        }
      }
      developers {
        edges {
          node {
            ... on Institution {
              ...InstitutionPartial
            }
            ... on User {
              ...UserPartial
            }
          }
        }
      }
      pendingDevelopers {
        edges {
          node {
            ... on Institution {
              ...InstitutionPartial
            }
            ... on User {
              ...UserPartial
            }
          }
        }
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateMethod($input: UpdateMethodInput!) {
  updateMethod(input: $input) {
    method {
      ...MethodPartial
    }
    errors {
      code
      message
      path
    }
  }
}
