fragment OpenIdConnectApplicationsPartial on OpenIdConnectApplication {
  id
  uuid
  clientId
  displayName
  postLogoutRedirectUri
  redirectUri
}

fragment OpenIdConnectAuthorizationPartial on OpenIdConnectAuthorization {
  id
  uuid
  creationDate
  status
  subject
  type
  isAuthorizedToDeleteNode
}

fragment OpenIdConnectTokenPartial on OpenIdConnectToken {
  id
  uuid
  creationDate
  expirationDate
  redemptionDate
  status
  subject
  type
  isAuthorizedToRevokeNode
}

fragment OpenIdConnectApplicationPartial on OpenIdConnectApplication {
  ...OpenIdConnectApplicationsPartial
  consentType
  endpoints
  grantTypes
  responseTypes
  scopes
  requirements
  isAuthorizedToManageNode
  owner {
    node {
      uuid
      name
    }
  }
  authorizations {
    edges {
      node {
        ...OpenIdConnectAuthorizationPartial
      }
    }
  }
  tokens {
    edges {
      node {
        ...OpenIdConnectTokenPartial
      }
    }
  }
}

query Applications {
  openIdConnectApplications {
    ...OpenIdConnectApplicationsPartial
  }
}

query Application($uuid: Uuid!) {
  openIdConnectApplication(id: $uuid) {
    ...OpenIdConnectApplicationPartial
  }
}

mutation CreateApplication($input: CreateOpenIdConnectApplicationInput!) {
  createOpenIdConnectApplication(input: $input) {
    application {
      ...OpenIdConnectApplicationPartial
    }
    clientSecret
    errors {
      code
      message
      path
    }
  }
}

mutation UpdateApplication($input: UpdateOpenIdConnectApplicationInput!) {
  updateOpenIdConnectApplication(input: $input) {
    application {
      ...OpenIdConnectApplicationPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ResetApplicationClientSecret(
  $input: ResetOpenIdConnectApplicationClientSecretInput!
) {
  resetOpenIdConnectApplicationClientSecret(input: $input) {
    clientSecret
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteApplication($input: DeleteOpenIdConnectApplicationInput!) {
  deleteOpenIdConnectApplication(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteAuthorization($input: DeleteOpenIdConnectAuthorizationInput!) {
  deleteOpenIdConnectAuthorization(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation RevokeToken($input: RevokeOpenIdConnectTokenInput!) {
  revokeOpenIdConnectToken(input: $input) {
    token {
      id
      status
    }
    errors {
      code
      message
      path
    }
  }
}
