fragment ApplicationPartial on Application {
  clientId
  displayName
  id
  permissions
  postLogoutRedirectUri
  redirectUri
  canCurrentUserManageApplication
}

fragment AuthorizationPartial on Authorization {
  creationDate
  id
  status
  subject
  type
  canCurrentUserDeleteAuthorization
}

fragment TokenPartial on Token {
  creationDate
  expirationDate
  id
  redemptionDate
  status
  subject
  type
  canCurrentUserRevokeToken
}

fragment ScopePartial on Scope {
  displayName
  id
  name
}
