import type * as Types from '../__generated__/graphql';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type AddUserMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  userId: Types.Scalars['Uuid']['input'];
}>;


export type AddUserMethodDeveloperMutation = { addUserMethodDeveloper: { __typename: 'AddUserMethodDeveloperPayload', errors: Array<{ __typename: 'AddUserMethodDeveloperError', code: Types.AddUserMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };

export type ConfirmUserMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  userId: Types.Scalars['Uuid']['input'];
}>;


export type ConfirmUserMethodDeveloperMutation = { confirmUserMethodDeveloper: { __typename: 'ConfirmUserMethodDeveloperPayload', errors: Array<{ __typename: 'ConfirmUserMethodDeveloperError', code: Types.ConfirmUserMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };

export type RemoveUserMethodDeveloperMutationVariables = Types.Exact<{
  methodId: Types.Scalars['Uuid']['input'];
  userId: Types.Scalars['Uuid']['input'];
}>;


export type RemoveUserMethodDeveloperMutation = { removeUserMethodDeveloper: { __typename: 'RemoveUserMethodDeveloperPayload', errors: Array<{ __typename: 'RemoveUserMethodDeveloperError', code: Types.RemoveUserMethodDeveloperErrorCode, message: string, path: Array<string> }> | null } };


export const AddUserMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"AddUserMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"userId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"addUserMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"userId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"userId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<AddUserMethodDeveloperMutation, AddUserMethodDeveloperMutationVariables>;
export const ConfirmUserMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"ConfirmUserMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"userId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"confirmUserMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"userId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"userId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<ConfirmUserMethodDeveloperMutation, ConfirmUserMethodDeveloperMutationVariables>;
export const RemoveUserMethodDeveloperDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"RemoveUserMethodDeveloper"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"userId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Uuid"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"removeUserMethodDeveloper"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"ObjectValue","fields":[{"kind":"ObjectField","name":{"kind":"Name","value":"methodId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"methodId"}}},{"kind":"ObjectField","name":{"kind":"Name","value":"userId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"userId"}}}]}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"errors"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"code"}},{"kind":"Field","name":{"kind":"Name","value":"message"}},{"kind":"Field","name":{"kind":"Name","value":"path"}}]}}]}}]}}]} as unknown as DocumentNode<RemoveUserMethodDeveloperMutation, RemoveUserMethodDeveloperMutationVariables>;