mutation AddUserMethodDeveloper($input: AddUserMethodDeveloperInput!) {
  addUserMethodDeveloper(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserMethodDeveloper($input: ConfirmUserMethodDeveloperInput!) {
  confirmUserMethodDeveloper(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveUserMethodDeveloper($input: RemoveUserMethodDeveloperInput!) {
  removeUserMethodDeveloper(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
