fragment UserPartial on User {
  id
  uuid
  name
  email
}

query Users {
  users {
    edges {
      node {
        ...UserPartial
      }
    }
  }
}

query User($uuid: Uuid!) {
  user(id: $uuid) {
    id
    uuid
    name
    email
    phoneNumber
    websiteLocator
    roles
    rolesCurrentUserCanAdd
    rolesCurrentUserCanRemove
    isAuthorizedToDeleteUser
    isAuthorizedToManageOpenIdConnect
    developedMethods {
      edges {
        node {
          id
          uuid
          name
        }
      }
    }
    pendingDevelopedMethods {
      edges {
        node {
          id
          uuid
          name
        }
      }
      isAuthorizedToConfirmEdge
    }
    representedInstitutions {
      edges {
        node {
          id
          uuid
          name
        }
      }
    }
    pendingRepresentedInstitutions {
      edges {
        node {
          id
          uuid
          name
        }
      }
      isAuthorizedToConfirmEdge
    }
  }
}

mutation RegisterUser($input: RegisterUserInput!) {
  registerUser(input: $input) {
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmail($input: ConfirmUserEmailInput!) {
  confirmUserEmail(input: $input) {
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmailChange($input: ConfirmUserEmailChangeInput!) {
  confirmUserEmailChange(input: $input) {
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RequestUserPasswordReset($input: RequestUserPasswordResetInput!) {
  requestUserPasswordReset(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ResetUserPassword($input: ResetUserPasswordInput!) {
  resetUserPassword(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteUser($input: DeleteUserInput!) {
  deleteUser(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation AddUserRole($input: AddUserRoleInput!) {
  addUserRole(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveUserRole($input: RemoveUserRoleInput!) {
  removeUserRole(input: $input) {
    errors {
      code
      message
      path
    }
  }
}
