#import "./common.graphql"

fragment UsersPartial on User {
  id
  uuid
  name
  contact {
    ...ContactInformationPartial
  }
  roles
  representedInstitutions {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      role
    }
  }
}

fragment UserPartial on User {
  id
  uuid
  name
  contact {
    ...ContactInformationPartial
  }
  roles
  rolesCurrentUserCanAdd
  rolesCurrentUserCanRemove
  isAuthorizedToDeleteUser
  isAuthorizedToManageOpenIdConnect
  userDevelopedMethods: developedMethods {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      isAuthorizedToRemoveEdge
    }
  }
  pendingUserDevelopedMethods: pendingDevelopedMethods {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToConfirmEdges
  }
  representedInstitutions {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      role
      isAuthorizedToRemoveEdge
    }
  }
  pendingRepresentedInstitutions {
    totalCount
    edges {
      node {
        id
        uuid
        name
      }
      role
      isAuthorizedToRemoveEdge
    }
    isAuthorizedToConfirmEdges
  }
}

query UserNames(
  $first: Int!
  $after: String
  $where: UserFilterInput
  $order: [UserSortInput!]
) {
  connection: users(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
}

query Users(
  $first: Int!
  $after: String
  $where: UserFilterInput
  $order: [UserSortInput!]
) {
  connection: users(
    first: $first
    after: $after
    where: $where
    order: $order
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        ...UsersPartial
      }
    }
  }
}

query User($uuid: Uuid!) {
  user(id: $uuid) {
    ...UserPartial
  }
}

mutation RegisterUser($input: RegisterUserInput!) {
  registerUser(input: $input) {
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmail($input: ConfirmUserEmailInput!) {
  confirmUserEmail(input: $input) {
    user {
      id
      contact {
        emailAddress
        isEmailAddressConfirmed
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmailChange($input: ConfirmUserEmailChangeInput!) {
  confirmUserEmailChange(input: $input) {
    user {
      id
      contact {
        emailAddress
        isEmailAddressConfirmed
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RequestUserPasswordReset($input: RequestUserPasswordResetInput!) {
  requestUserPasswordReset(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ResetUserPassword($input: ResetUserPasswordInput!) {
  resetUserPassword(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ResendUserEmailConfirmation(
  $input: ResendUserEmailConfirmationInput!
) {
  resendUserEmailConfirmation(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteUser($input: DeleteUserInput!) {
  deleteUser(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation AddUserRole($input: AddUserRoleInput!) {
  addUserRole(input: $input) {
    user {
      id
      roles
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveUserRole($input: RemoveUserRoleInput!) {
  removeUserRole(input: $input) {
    user {
      id
      roles
    }
    errors {
      code
      message
      path
    }
  }
}
