mutation AddUserMethodDeveloper($input: AddUserMethodDeveloperInput!) {
  addUserMethodDeveloper(input: $input) {
    developedMethodEdge {
      node {
        ...MethodPartial
      }
    }
    methodDeveloperEdge {
      node {
        ...UserPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserMethodDeveloper($input: ConfirmUserMethodDeveloperInput!) {
  confirmUserMethodDeveloper(input: $input) {
    developedMethodEdge {
      node {
        ...MethodPartial
      }
    }
    methodDeveloperEdge {
      node {
        ...UserPartial
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveUserMethodDeveloper($input: RemoveUserMethodDeveloperInput!) {
  removeUserMethodDeveloper(input: $input) {
    method {
      ...MethodPartial
    }
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}
