fragment UsersPartial on User {
  id
  uuid
  name
  contact {
    emailAddress
    isEmailAddressConfirmed
  }
}

fragment UserPartial on User {
  id
  uuid
  name
  contact {
    emailAddress
    isEmailAddressConfirmed
    phoneNumber
    isPhoneNumberConfirmed
    websiteLocator
  }
  roles
  rolesCurrentUserCanAdd
  rolesCurrentUserCanRemove
  isAuthorizedToDeleteUser
  isAuthorizedToManageOpenIdConnect
  developedMethods {
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
  pendingDevelopedMethods {
    edges {
      node {
        id
        uuid
        name
      }
    }
    isAuthorizedToConfirmEdges
  }
  representedInstitutions {
    edges {
      node {
        id
        uuid
        name
      }
    }
  }
  pendingRepresentedInstitutions {
    edges {
      node {
        id
        uuid
        name
      }
    }
    isAuthorizedToConfirmEdges
  }
}

query UserNames {
  users {
    edges {
      node {
        uuid
        name
      }
    }
  }
}

query Users {
  users {
    edges {
      node {
        ...UsersPartial
      }
    }
  }
}

query User($uuid: Uuid!) {
  user(id: $uuid) {
    ...UserPartial
  }
}

mutation RegisterUser($input: RegisterUserInput!) {
  registerUser(input: $input) {
    user {
      ...UserPartial
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmail($input: ConfirmUserEmailInput!) {
  confirmUserEmail(input: $input) {
    user {
      id
      contact {
        emailAddress
        isEmailAddressConfirmed
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation ConfirmUserEmailChange($input: ConfirmUserEmailChangeInput!) {
  confirmUserEmailChange(input: $input) {
    user {
      user {
        id
        contact {
          emailAddress
          isEmailAddressConfirmed
        }
      }
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RequestUserPasswordReset($input: RequestUserPasswordResetInput!) {
  requestUserPasswordReset(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation ResetUserPassword($input: ResetUserPasswordInput!) {
  resetUserPassword(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation DeleteUser($input: DeleteUserInput!) {
  deleteUser(input: $input) {
    errors {
      code
      message
      path
    }
  }
}

mutation AddUserRole($input: AddUserRoleInput!) {
  addUserRole(input: $input) {
    user {
      id
      roles
    }
    errors {
      code
      message
      path
    }
  }
}

mutation RemoveUserRole($input: RemoveUserRoleInput!) {
  removeUserRole(input: $input) {
    user {
      id
      roles
    }
    errors {
      code
      message
      path
    }
  }
}
