# Generated by Django 2.2.5 on 2019-09-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='User',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='icon_instit_identif_40a2ed_idx',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['identifier'], name='icon_user_identif_4be493_idx'),
        ),
    ]
