# Generated by Django 2.2.5 on 2019-09-10 14:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icon.Institution')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=16, unique=True, validators=[django.core.validators.MinLengthValidator(4)])),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icon.Institution')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['identifier'], name='icon_instit_identif_40a2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['identifier'], name='icon_produc_identif_d12f31_idx'),
        ),
        migrations.AddIndex(
            model_name='measurementmethod',
            index=models.Index(fields=['identifier'], name='icon_measur_identif_04454f_idx'),
        ),
    ]
