using System;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Metabase.Controllers
{
    public sealed class AntiforgeryController : Controller
    {
        private const string CookieKey = "XSRF-TOKEN";

        private readonly IAntiforgery _antiforgeryService;

        public AntiforgeryController(IAntiforgery antiforgeryService)
        {
            _antiforgeryService = antiforgeryService;
        }

        [HttpGet("~/antiforgery/token")]
        // [Authorize]
        public IActionResult Token()
        {
            var tokens = _antiforgeryService.GetAndStoreTokens(HttpContext);
            HttpContext.Response.Cookies.Append(
                CookieKey,
                tokens.RequestToken ?? throw new InvalidOperationException("The request token supposed to be generated by the antiforgery service is null."),
                new CookieOptions
                {
                    HttpOnly = false
                }
            );
            return new StatusCodeResult(StatusCodes.Status200OK);
        }
    }
}