using System;
using System.Threading;
using System.Threading.Tasks;
using Metabase.Authentication;
using Microsoft.AspNetCore.Antiforgery;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Metabase.Controllers;

// For gotchas regarding antiforgery tokens read
// [Clarity around IAntiforgery and ValidateAntiForgeryToken](https://github.com/dotnet/aspnetcore/issues/2783)
public sealed class AntiforgeryController(
    IAntiforgery antiforgeryService,
    AuthenticationHandler authenticationHandler
)
: Controller
{
    private const string XsrfCookieKey = "XSRF-TOKEN";

    private readonly IAntiforgery _antiforgeryService = antiforgeryService;

    private readonly CookieOptions _xsrfCookieOptions =
        new()
        {
            HttpOnly = false,
            SameSite = SameSiteMode.Strict
        };

    [HttpGet("~/antiforgery/token")]
    public async Task<IActionResult> Token(
        CancellationToken cancellationToken
    )
    {
        await authenticationHandler.AuthenticateAsync(HttpContext, cancellationToken);
        var tokens = _antiforgeryService.GetAndStoreTokens(HttpContext);
        HttpContext.Response.Cookies.Append(
            XsrfCookieKey,
            tokens.RequestToken ??
            throw new InvalidOperationException(
                "The request token supposed to be generated by the antiforgery service is null."),
            _xsrfCookieOptions
        );
        return new StatusCodeResult(StatusCodes.Status200OK);
    }
}