@startuml "Class Diagram"

skinparam componentStyle uml2

class Component {
  +Uuid id
  +Uuid creatorId
}

class ComponentInformation {
  +String name
  +String abbreviation
  +String description
  +Enum categories
}

class ComponentAssembly {
  +Uuid id
}

class ComponentManufacturer {
  +Uuid id
}

class ComponentManufacturerMarketingInformation {
}

class ComponentVersion {
  +Uuid id
  +String name
}

class ComponentVersionAssembly {
  +Uuid id
}

class ComponentVersionManufacturer {
  +Uuid id
}

class ComponentVersionManufacturerMarketingInformation {
}

class Institution {
  +Uuid id
  +String publicKey
  +Enum state
}

class InstitutionInformation {
  +String name
  +String abbreviation
  +String description
  +Url websiteLocator
}

class InstitutionRepresentative {
  +Uuid id
}

class User {
  +Uuid id
}

class Database {
  +Uuid id
  +String name
  +String description
  +Url locator
}

class Standard {
  +Uuid id
  +String title
  +String abstract
  +String section
  +String year
  +String prefix
  +String mainNumber
  +String suffix
  +Enum standardizers
  +Url locator
}

class Method {
  +Uuid id
}

class MethodVersion {
  +Uuid id
}

class MethodInformation {
  +String name
  +String description
  +Url publicationLocator
  +Url codeLocator
  +Enum categories
}

class MethodDeveloper {
  +Uuid id
}

class Stakeholder {
  /' +Uuid id '/
}

class Person {
  +Uuid id
  +String name
}

class ContactInformation {
  +String phoneNumber
  +String postalAddress
  +Email emailAddress
  +Url websiteLocator
}

class Affiliation {
}

ComponentAssembly "*" --* "1" Component : sub
ComponentAssembly "*" --* "1" Component : super
Component "1" *-- "*" ComponentVersion
Component "1" *-- "1" ComponentInformation
Component "1" *-- "*" ComponentManufacturer
ComponentManufacturer "*" -- "1" Institution
ComponentManufacturer "1" *-- "1" ComponentManufacturerMarketingInformation
ComponentManufacturerMarketingInformation "1" *-- "0..1" ComponentInformation
ComponentManufacturerMarketingInformation "1" *-- "0..1" InstitutionInformation
ComponentVersionAssembly "*" --* "1" ComponentVersion : sub
ComponentVersionAssembly "*" --* "1" ComponentVersion : super
ComponentVersion "1" *-- "*" ComponentVersionManufacturer
ComponentVersion "1" *-- "1" ComponentInformation
ComponentVersionManufacturer "*" -- "1" Institution
ComponentVersionManufacturer "1" *-- "1" ComponentVersionManufacturerMarketingInformation
ComponentVersionManufacturerMarketingInformation "1" *-- "0..1" ComponentInformation
ComponentVersionManufacturerMarketingInformation "1" *-- "0..1" InstitutionInformation
Institution "1" *-- "*" InstitutionRepresentative
Institution "1" *-- "1" InstitutionInformation
Institution "1" *-- "*" Database
User "1" *-- "*" InstitutionRepresentative
Method "1" *-- "1" MethodInformation
Method "1" *-- "*" MethodVersion
MethodVersion "1" *-- "1" MethodInformation
MethodInformation -- "1" Standard
MethodDeveloper "*" -- "1" Method
MethodDeveloper "*" -- "1" Stakeholder
Stakeholder "*" -- "1" Method
Person "*" *-- "1" ContactInformation
Affiliation "*" --* "1" Person
Affiliation "*" --* "1" Institution
Stakeholder <|-- Person
Stakeholder <|-- Institution

@enduml
