mutation createInstitution(
  $institutionId: Uuid,
  $name: String!
  $abbreviation: String
  $description: String!
  $contact: ContactInformationInput
  $ownerIds: [Uuid!]!
  $managerId: Uuid
) {
  createInstitution(
    input: {
      institutionId: $institutionId
      name: $name
      abbreviation: $abbreviation
      description: $description
      contact: $contact
      ownerIds: $ownerIds
      managerId: $managerId
    }
  ) {
    institution {
      id
      uuid
      name
      abbreviation
      description
      contact {
        phoneNumber
        postalAddress
        emailAddress
        websiteLocator
      }
    }
    errors {
      code
      message
      path
    }
  }
}
