import {
  ApolloClient,
  InMemoryCache,
  HttpLink,
  ErrorLike,
  CombinedGraphQLErrors,
  CombinedProtocolErrors,
  ApolloLink,
} from "@apollo/client";
import { ErrorLink } from "@apollo/client/link/error";
import { Defer20220824Handler } from "@apollo/client/incremental";
import { LocalState } from "@apollo/client/local-state";
import { PersistedQueryLink } from "@apollo/client/link/persisted-queries";
import { SetContextLink } from "@apollo/client/link/context";
import { sha256 } from "crypto-hash";
import fragmentMatcherTypes from "../__generated__/fragmentMatcherTypes"; // generated by `fragment-matcher` plugin
import { GraphQLFormattedError } from "graphql";
import { map } from "rxjs";

const AntiforgeryCookieKey = "XSRF-TOKEN";
const AntiforgeryHeaderName = "X-XSRF-TOKEN";
const GraphQlEndpointPath = "/graphql/";

function extractCookie(name: string, cookies: string): string | null {
  return (
    cookies
      .split(";")
      .map((cookie) => cookie.trim())
      .filter((cookie) => {
        return cookie.substring(0, name.length + 1) === `${name}=`;
      })
      .map((cookie) => {
        return decodeURIComponent(cookie.substring(name.length + 1));
      })[0] || null
  );
}

// Log any GraphQL errors, protocol errors, or network error that occurred
// inspired by https://www.apollographql.com/docs/react/api/link/apollo-link-error
const logErrorsLink = new ErrorLink(({ error }) => {
  if (CombinedGraphQLErrors.is(error)) {
    error.errors.forEach(({ message, locations, path }) =>
      console.log(
        `[GraphQL Error]: Message: ${message}, Location: ${locations}, Path: ${path}`,
      ),
    );
  } else if (CombinedProtocolErrors.is(error)) {
    error.errors.forEach(({ message, extensions }) =>
      console.error(
        `[Protocol Error]: Message: ${message}, Extensions: ${JSON.stringify(
          extensions,
        )}`,
      ),
    );
  } else {
    console.error(`[Network Error]: ${error}`);
  }
});

type AuthErrorCode = "AUTH_NOT_AUTHENTICATED";

type AuthGraphQlError = GraphQLFormattedError & {
  extensions: {
    code: AuthErrorCode;
  };
};

function isAuthError(error: GraphQLFormattedError): error is AuthGraphQlError {
  return error.extensions?.code === "AUTH_NOT_AUTHENTICATED";
}

const filterAuthErrorsLink = new ApolloLink((operation, forward) =>
  forward(operation).pipe(
    map((response) => {
      if (response.errors) {
        response.errors = response.errors.filter(
          (error): error is Exclude<typeof error, AuthGraphQlError> =>
            !isAuthError(error),
        );
      }
      return response;
    }),
  ),
);

export function extractAntiforgeryTokenFromCookie(): string | null {
  return extractCookie(AntiforgeryCookieKey, document.cookie);
}

// inspired by https://www.apollographql.com/docs/react/networking/authentication#header
const antiforgeryLink = new SetContextLink(({ headers }) => {
  const antiforgeryToken = extractAntiforgeryTokenFromCookie();
  if (antiforgeryToken) {
    return {
      headers: {
        ...headers,
        [AntiforgeryHeaderName]: antiforgeryToken,
      },
    };
  }
  return { headers: headers };
});

const persistedQueryLink = new PersistedQueryLink({
  sha256,
  useGETForHashedQueries: false,
});

const httpLink = new HttpLink({
  uri: GraphQlEndpointPath,
  useGETForQueries: false, // Use `POST` for queries to avoid "414 Request-URI Too Large" errors
  credentials: "same-origin", // https://www.apollographql.com/docs/react/networking/authentication#cookie
  headers: { accept: "application/json" },
});

const apolloLink = filterAuthErrorsLink
  .concat(logErrorsLink)
  .concat(antiforgeryLink)
  .concat(persistedQueryLink)
  .concat(httpLink);

export const apolloClient = new ApolloClient({
  ssrMode: false,
  link: apolloLink,
  cache: new InMemoryCache({
    possibleTypes: fragmentMatcherTypes.possibleTypes,
  }),
  localState: new LocalState({}),
  incrementalHandler: new Defer20220824Handler(),
  defaultOptions: {
    watchQuery: {
      errorPolicy: "all" as const,
    },
    query: {
      errorPolicy: "all" as const,
    },
    mutate: {
      errorPolicy: "all" as const,
    },
  },
});

// See https://www.apollographql.com/docs/react/data/error-handling
export function stringifyApolloError(error: ErrorLike) {
  // if (CombinedGraphQLErrors.is(error)) {
  //   return `Name(${error.name}); Message(${error.message}); Extensions(${error.extensions
  //     }); Stack(${error.stack}); GraphQL Errors(${error.errors
  //       .map(
  //         (e) =>
  //           `[Message(${e.message}); Path(${e.path?.join(
  //             ".",
  //           )}); Locations(${e.locations?.join(", ")}); Extensions(${e.extensions
  //           })]`,
  //       )
  //       .join(", ")})`;
  // } if (CombinedProtocolErrors.is(error)) {
  // Handle multipart subscription protocol errors
  // } if (LocalStateError.is(error)) {
  // Handle errors thrown by the `LocalState` class
  // } if (ServerError.is(error)) {
  // Handle server HTTP errors
  // } if (ServerParseError.is(error)) {
  // Handle JSON parse errors
  // } if (UnconventionalError.is(error)) {
  // Handle errors thrown by irregular types
  return `${error.name}: ${error.message}`;
}

/*
Copy the contents of this block into a `.d.ts` file in your project to enable correct response types in your custom links.
If you do not use the `@defer` directive in your application, you can safely remove this block.

import "@apollo/client";
import { Defer20220824Handler } from "@apollo/client/incremental";
declare module "@apollo/client" {
  export interface TypeOverrides extends Defer20220824Handler.TypeOverrides {}
}
*/
